### ISSUE TITLE
Create pull request command opens a URL with incorrect escaping

### ISSUE THREAD

**Issue by slieschke** [jesseduffield/lazygit#3064] opened 2023-10-11 18:31 UTC
**Describe the bug**
If I use the `o` shortcut to create a pull request to GitLab for a branch that contains a slash in its name the new merge request screen does not successfully load.

**To Reproduce**

1. Create a branch named `improvement/improve-usage-docs` for a GitLab repo
3. Use `o` to create a pull request

The pull request page opened in the browser fails. The URL opened in the browser is:
`https://gitlab.com/<group>/<repo>/-/merge_requests/new?merge_request%5Bsource_branch%5D=improvement%252Fimprove-usage-docs`

**Expected behavior**
The pull request URL opened in the browser should be:
`https://gitlab.com/<group>/<repo>/-/merge_requests/new?merge_request%5Bsource_branch%5D=improvement%2Fimprove-usage-docs`

**Screenshots**
![CleanShot 2023-10-11 at 14 16 15](https://github.com/jesseduffield/lazygit/assets/742941/d59f2706-d182-42e5-ae9d-b477bb5f6421)

**Version info:**
```
> lazygit --version
commit=, build date=, build source=homebrew, version=0.40.2, os=darwin, arch=amd64, git version=2.42.0
> git --version
git version 2.42.0
```

**Additional context**
If I use `<c-y>` to copy the pull request creation URL, my clipboard contains:
`https://gitlab.com/<group>/<repo>/-/merge_requests/new?merge_request[source_branch]=improvement%2Fimprove-usage-docs`

and if I then paste that directly to my browser the URL the address bar displays:
`https://gitlab.com/<group>/<repo>/-/merge_requests/new?merge_request%5Bsource_branch%5D=improvement/improve-usage-docs`

I've worked around this in the meantime by adding this targeted hack to the lazygit configuration:
```
os:
  openLink: open "$(echo "{{link}}" | sed 's/%2F/\//g')"
```

**Comment by mark2185** [comment] 2023-10-11 19:18
Thanks for the report (and the workaround!), but since it's a duplicate of #3052 I'll close it.

**Closed by mark2185** 2023-10-11 19:18 UTC
Labels: bug
