### ISSUE TITLE
Continue/abort/skip for reverting and cherry picking

### ISSUE THREAD

**Issue by OliverJAsh** [jesseduffield/lazygit#4127] opened 2024-12-25 09:30 UTC
**Is your feature request related to a problem? Please describe.**
When I revert or cherry-pick a commit and have merge conflicts, after resolving the conflicts I need to run `git revert --continue` or `git cherry-pick --continue`.

**Describe the solution you'd like**
It would be nice if lazygit provided this functionality, similar to the options for continue merge / continue rebase.

**Describe alternatives you've considered**

**Additional context**

**Comment by stefanhaller** [comment] 2024-12-25 09:47
Oh yes. This is a duplicate of #1807 though.

I started working on this about half a year ago (or more), and made reasonable progress, but got distracted by other things that I found more important. It's a lot of work, but it's pretty high up on my list of things to pick up again.

**Closed** 2024-12-25 09:58 UTC
Labels: enhancement
