### ISSUE TITLE
Panic error after installing in MacOS

### ISSUE THREAD

**Issue by vinill** [jesseduffield/lazygit#174] opened 2018-08-17 12:53 UTC
![screen shot 2018-08-17 at 14 50 51](https://user-images.githubusercontent.com/9474553/44267036-040d2b00-a22d-11e8-833b-7c6b9e7a19c6.png)

**Comment by glvr182** [comment] 2018-08-17 13:18
main.go Line 66 - 68 state : 
```
66 : app, err := app.NewApp(appConfig)
67 : app.Log.Info(err)
68 : app.GitCommand.SetupGit()
```
So my guess would be that when app.log tried to log err, err was nil.
What is strange is when I try to reproduce this error I can't seem to get it.

**Comment by remyabel** [comment] 2018-08-17 13:42
@vinill Can you apply this patch and tell us if the error goes away?

```diff
diff --git a/main.go b/main.go
index c7fec1a..6f9f3fb 100644
--- a/main.go
+++ b/main.go
@@ -64,7 +64,9 @@ func main() {
                Debug:     *debuggingFlag,
        }
        app, err := app.NewApp(appConfig)
-       app.Log.Info(err)
+       if err != nil {
+               app.Log.Info(err)
+       }
        app.GitCommand.SetupGit()
        app.Gui.RunWithSubprocesses()
 }
```
Copy/paste it into a file named patch and run `git apply patch; go build; ./lazygit`

**Comment by jesseduffield** [comment] 2018-08-18 09:30
@remyabel ah I think I see what's happening here. An error has occured when making the app, but that error occurred before the logger was added to the app struct, meaning that we're getting a nil pointer dereference

**Comment by jesseduffield** [comment] 2018-08-18 09:45
actually turns out the logger probably is there, but when there's an error, we're not returning the app.
Gonna fix this in https://github.com/jesseduffield/lazygit/pull/180 (though there'll probably be more troubleshooting here to determine why the the call to NewApp() is failing in the first place)

**Comment by gomjellie** [comment] 2018-08-18 18:40
I have same issue on OS X Elcapitan

it seem that versions after 1.6.1 has that issue

this is the way i downgraded to **1.6.1 version**


```
wget "https://github.com/jesseduffield/lazygit/releases/download/v0.1.61/lazygit_0.1.61_Darwin_x86_64.tar.gz"
tar -xvzf ./lazygit_0.1.61_Darwin_x86_64.tar.gz
cp ./lazygit /usr/local/bin/lazygit
```

**Comment by jesseduffield** [comment] 2018-08-19 05:49
@gomjellie do you still get the error from the latest version?

**Comment by gomjellie** [comment] 2018-08-19 09:04
i just reinstalled current version via brew ('brew reinstall lazygit')

```
brew info lazygit
jesseduffield/lazygit/lazygit: stable 0.1.66
A simple terminal UI for git commands, written in Go
https://github.com/jesseduffield/lazygit/
/usr/local/Cellar/lazygit/0.1.66 (5 files, 12.0MB) *
  Built from source on 2018-08-19 at 18:00:40
From: https://github.com/jesseduffield/homebrew-lazygit/blob/master/lazygit.rb
```

**0.1.66 version** still not working on mine

**Comment by gomjellie** [comment] 2018-08-19 09:05
this is the error log
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1573f4b]

goroutine 1 [running]:
main.main()
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/main.go:55 +0x14b
```

**Comment by gomjellie** [comment] 2018-08-19 14:55
**version 1.7.72** make panic on mine

```
panic: Could not detect Language

goroutine 1 [running]:
main.main()
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/main.go:60 +0x305
```

**Comment by remyabel** [comment] 2018-08-19 15:07
Looks like that error originates from here: https://github.com/cloudfoundry-attic/jibber_jabber Please open an issue there.

Meanwhile, what's the output when you run the `locale` command?

**Comment by gomjellie** [comment] 2018-08-19 15:14
```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by gomjellie** [comment] 2018-08-19 16:55
@remyabel thanks! changing `LC_ALL` to `en_US.UTF-8` works!

**Comment by glvr182** [comment] 2018-08-19 17:48
@gomjellie So I understand everything goes solid now?

**Comment by glvr182** [comment] 2018-08-19 19:01
@gomjellie Good to hear!

**Comment by glvr182** [comment] 2018-08-19 19:03
@vinill Is the issue solved in the latest version?

**Comment by Piot** [comment] 2018-08-19 20:12
It is not fixed in 0.1.73 @vinill 

But it works by specifying LC_ALL as @remyabel suggested.

```bash
LC_ALL="C" lazygit 
```

**Comment by jesseduffield** [comment] 2018-08-19 23:37
Any objections to making lazygit use 'C' as the default when the jibber jabber package fails to find a language?

**Comment by cdnil** [comment] 2018-08-20 03:13
0.1.73
```
panic: Could not detect Language

goroutine 1 [running]:
main.main()
	/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/main.go:44 +0x28a
```

```
jesseduffield/lazygit/lazygit: stable 0.1.73
A simple terminal UI for git commands, written in Go
https://github.com/jesseduffield/lazygit/
/usr/local/Cellar/lazygit/0.1.73 (5 files, 12MB) *
  Built from source on 2018-08-20 at 11:09:49
From: https://github.com/jesseduffield/homebrew-lazygit/blob/master/lazygit.rb
```

**Comment by jesseduffield** [comment] 2018-08-20 03:29
this is fixed (hopefully) in https://github.com/jesseduffield/lazygit/pull/191
Please install the latest release and let me know if that resolves your issue

**Comment by vinill** [comment] 2018-08-20 07:46
The new version fixes the problem.
@jesseduffield

**Closed** 2018-08-20 07:47 UTC

**Comment by Piot** [comment] 2018-08-20 16:45
Confirmed to be working in 0.1.76
