### ISSUE TITLE
Quitting doesn't work any more

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#1680] opened 2022-01-15 09:23 UTC
**Describe the bug**
Attempting to quit shows an error message

**To Reproduce**
1. Hit 'q' to quit
2. Hit enter

**Expected behavior**
App quits

**Screenshots**

https://user-images.githubusercontent.com/191335/149616707-034ef752-946f-4a4f-ae0c-a948d6029752.MOV

**Desktop (please complete the following information):**
 - OS: macOS
 - Lazygit master 7a690f9078637561425cf3c1143da88b1769cf16

**Additional context**
config: https://gist.github.com/ebc02d5df581cdfbed915a44abfe9c80

**Comment by jesseduffield** [comment] 2022-01-15 09:24
hmm, can't reproduce on my end. Are you pressing 'q' to quit?

**Comment by jesseduffield** [comment] 2022-01-15 09:26
I take it back: just used your config and I've reproduced. One moment!

**Comment by jesseduffield** [comment] 2022-01-15 09:31
fixed in https://github.com/jesseduffield/lazygit/pull/1681. I've added an integration test to prevent further regressions. Apologies for the inconvenience!

**Comment by peppy** [comment] 2022-01-15 09:33
Linked PR fixes the issue, thanks!

**Closed** 2022-01-15 09:35 UTC
Labels: bug
