### ISSUE TITLE
lazygit on symbol link (or soft link) crash

### ISSUE THREAD

**Issue by 66RING** [jesseduffield/lazygit#2989] opened 2023-09-05 12:15 UTC
**Describe the bug**
open lazygit on a symbol link (or soft link) folder will crash, which return `*errors.errorString Must open lazygit in a git repository`.

**To Reproduce**

1. create file tree like this:

```
.(/a/git/repo)
├── folder1
└── folder2(will be linked to some where)
```

2. symbol link `folder2` to somewhere like:

```
ln -s /a/git/repo/folder2 /a/
```
3. open lazygit then crash

```
$ pwd
/a/folder2
$ lazygit
2023/09/05 20:04:30 An error occurred! Please create an issue at: https://github.com/jesseduffield/lazygit/issues

*errors.errorString Must open lazygit in a git repository
github.com/jesseduffield/lazygit/pkg/commands/git.go:235 (0x55cd13398da6)
github.com/jesseduffield/lazygit/pkg/commands/git.go:87 (0x55cd13397936)
github.com/jesseduffield/lazygit/pkg/gui/gui.go:271 (0x55cd134c76eb)
github.com/jesseduffield/lazygit/pkg/gui/gui.go:656 (0x55cd134ca2db)
github.com/jesseduffield/lazygit/pkg/gui/gui.go:675 (0x55cd134ca9c5)
github.com/jesseduffield/lazygit/pkg/utils/utils.go:108 (0x55cd132260fc)
github.com/jesseduffield/lazygit/pkg/gui/gui.go:674 (0x55cd134ca90e)
github.com/jesseduffield/lazygit/pkg/app/app.go:263 (0x55cd134f657d)
github.com/jesseduffield/lazygit/pkg/app/app.go:48 (0x55cd134f6512)
github.com/jesseduffield/lazygit/pkg/app/entry_point.go:150 (0x55cd134f86ea)
github.com/jesseduffield/lazygit/main.go:23 (0x55cd134f9e78)
runtime/internal/atomic/types.go:194 (0x55cd12e53eb2)
runtime/asm_amd64.s:1650 (0x55cd12e84121)
```

**Expected behavior**
Find the real path of this symbolic link and lazygit on that folder.

**Screenshots**

```
2023/09/05 20:04:30 An error occurred! Please create an issue at: https://github.com/jesseduffield/lazygit/issues

*errors.errorString Must open lazygit in a git repository
github.com/jesseduffield/lazygit/pkg/commands/git.go:235 (0x55cd13398da6)
github.com/jesseduffield/lazygit/pkg/commands/git.go:87 (0x55cd13397936)
github.com/jesseduffield/lazygit/pkg/gui/gui.go:271 (0x55cd134c76eb)
github.com/jesseduffield/lazygit/pkg/gui/gui.go:656 (0x55cd134ca2db)
github.com/jesseduffield/lazygit/pkg/gui/gui.go:675 (0x55cd134ca9c5)
github.com/jesseduffield/lazygit/pkg/utils/utils.go:108 (0x55cd132260fc)
github.com/jesseduffield/lazygit/pkg/gui/gui.go:674 (0x55cd134ca90e)
github.com/jesseduffield/lazygit/pkg/app/app.go:263 (0x55cd134f657d)
github.com/jesseduffield/lazygit/pkg/app/app.go:48 (0x55cd134f6512)
github.com/jesseduffield/lazygit/pkg/app/entry_point.go:150 (0x55cd134f86ea)
github.com/jesseduffield/lazygit/main.go:23 (0x55cd134f9e78)
runtime/internal/atomic/types.go:194 (0x55cd12e53eb2)
runtime/asm_amd64.s:1650 (0x55cd12e84121)
```

**Version info:**
lazygit version

```
commit=v0.40.2, build date=2023-08-12T17:47:33Z, build source=binaryRelease, version=0.40.2, os=linux, arch=amd64, git version=2.42.0
```

git version

```
git version 2.42.0
```

**Comment by mark2185** [comment] 2023-09-05 12:40
Duplicate of #2958.

Also there's a workaround in the meantime, provided by the author of that issue:

>And lazygit works as expected. Using a helper script like this:
>```
>#!/bin/zsh
>cd $(readlink -f .)
>/usr/local/bin/lazygit "$@"
>```
>works around the issue.

**Closed by mark2185** 2023-09-05 12:40 UTC
Labels: bug
