### ISSUE TITLE
Fast commits panel switching on large commit 

### ISSUE THREAD

**Issue by pechorin** [jesseduffield/lazygit#156] opened 2018-08-15 18:43 UTC
Hello, thanks for great utility. I really enjoy it. But i have problem which is related to my current project. 

Really big commit in `Commits panel` freeze whole program when this commit selected. What kind of commits i'm talking about? For example: compiled javascript files potentially can be very huge (and they are). And they can not be git ignored in some projects. 

**Describe the solution you'd like**
Maybe pre-processing next `Diff panel` right after switching to current commit has finished? (not memory effective)
Or ability to ignore diff for files specified in special config?

Thanks.

**Comment by remyabel** [comment] 2018-08-15 19:08
The most common data structure for text editors is the rope. Here's a [text editor written in Go](https://github.com/zyedidia/micro/blob/master/cmd/micro/buffer.go) that uses a rope for handling large files.

**Comment by fiendish** [comment] 2018-08-15 20:41
this looks like a near dupe of #39 ?

**Closed** 2018-08-15 20:42 UTC
