### ISSUE TITLE
Renaming a branch has different functionality from creating a branch

### ISSUE THREAD

**Issue by calthejuggler** [jesseduffield/lazygit#2988] opened 2023-09-05 12:07 UTC
**Describe the bug**
When creating a branch, the "New Branch Name" dialog pops up. I can quickly type: `my branch name` and hit enter and lazygit seems to automatically convert it to `my-branch-name`. I love this feature because I can type spaces quicker than I can type `-`s. When renaming a branch though, if I changed `my-branch-name` to `my-branch-name without a typo`, I get an invalid branch name error.

There may be a reason for this that I don't understand, but if it could be added it would be great 🙂 I'd even be happy to attempt to put in a PR myself (although I've never touched Golang, so it might take me a while 😅)

Let me know what you think!

**To Reproduce**

1. Open Lazygit
2. Create a branch and put spaces in the branch name (eg. `my branch name`)
3. The branch `my-branch-name` is created
4. Rename that branch to `my-branch name` and hit enter
5. See `fatal: 'my-branch name' is not a valid branch name` error

**Expected behavior**
`my-branch name` would be changed to `my-branch-name` when renaming the branch.

**Screenshots**
N/A

**Version info:**
Lazygit:
commit=5e388e21c8ca6aa883dbcbe45c47f6fdd5116815, build date=2023-08-07T14:05:48Z, build source=binaryRelease, version=0.40.2, os=darwin, arch=arm64, git version=2.39.2
Git:
git version 2.39.2

**Additional context**
N/A

**Comment by mark2185** [comment] 2023-09-05 12:12
This is a duplicate of #2101 and it's still up for grabs!

Let us know if you need any pointers, but this shouldn't be too difficult, if you need any more reassurance, here's [the contributing guide](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md) :)

**Comment by calthejuggler** [comment] 2023-09-05 12:28
> This is a duplicate of #2101 and it's still up for grabs!
> 
> Let us know if you need any pointers, but this shouldn't be too difficult, if you need any more reassurance, here's [the contributing guide](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md) :)

Thanks @mark2185 🙂  I believe I've done it, but when I try to push my local branch I'm getting a 403 error: `Permission to jesseduffield/lazygit.git denied to calthejuggler`

Do I need some sort of permissions from your side?

**Comment by calthejuggler** [comment] 2023-09-05 12:43
> Well, you have to _fork_ the repository and then open a PR to this repository :)

That's embarrassing 🤦 Tell me you've never contributed to OSS before without telling me you've never contributed to OSS before 😂  

Glad for lazygit to be the first! 🙂 

The PR is in at https://github.com/jesseduffield/lazygit/pull/2990

**Comment by mark2185** [comment] 2023-09-05 12:51
Don't worry, we all start somewhere! :)

**Comment by mark2185** [comment] 2023-09-09 08:01
Closed by #2990 .

Thanks for the contribution! :)

**Closed by mark2185** 2023-09-09 08:01 UTC
Labels: bug
