### ISSUE TITLE
Patch pane, can`n not open file.

### ISSUE THREAD

**Issue by friendbear** [jesseduffield/lazygit#1382] opened 2021-07-11 02:33 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'Patch pane'
2. Press x, select o
  * **File not found error**
<img width="704" alt="lazygit 2021-07-11 at 11 30 36" src="https://user-images.githubusercontent.com/4956799/125181015-bacee080-e23b-11eb-9c0d-8ff1c4a0b2ef.png">

**Expected behavior**

**Screenshots**
<img width="719" alt="lazygit 2021-07-11 at 11 17 19" src="https://user-images.githubusercontent.com/4956799/125180911-8eff2b00-e23a-11eb-97ac-3e01d4ffea81.png">

**Desktop (please complete the following information):**
 - OS: [macOS 11.4]
 - Lazygit Version [ommit=f91adf026bfbddc9505d6d84d3fabc80d49c7ca0, build date=2021-06-05T04:16:14Z, build source=binaryRelease, version=0.28.2, os=darwin, arch=amd64]
- ~~The last commit id if you built project from sources (run : ```git-rev parse HEAD```)~~

**Additional context**

**Comment by fsmiamoto** [comment] 2021-08-01 17:19
@friendbear I think this is a duplicate of #1187, so we might close this one :)

**Comment by friendbear** [comment] 2021-08-01 20:46
Thanks for the reply. @fsmiamoto

**Closed** 2021-08-25 12:37 UTC
Labels: bug
