### ISSUE TITLE
Custom pager(delta) not support in single file path

### ISSUE THREAD

**Issue by LovesAsuna** [jesseduffield/lazygit#3655] opened 2024-06-12 11:51 UTC
**Describe the bug**
Custom pager(delta) not support in single file patch

**To Reproduce**
1. Go to 'the forth window(DIff files)'
2. Click on any file
3. See error(the original diff view)

**Expected behavior**
single diff file using delta pager

**Screenshots**
<img width="1920" alt="image" src="https://github.com/jesseduffield/lazygit/assets/32810896/bb8fa19b-f954-449c-bfb0-4dd26fa49daa">
<img width="1920" alt="image" src="https://github.com/jesseduffield/lazygit/assets/32810896/67cf405e-204a-44c9-bce7-4b85ddd743e8">

**Version info:**
_Run `lazygit --version` and paste the result here_
commit=6fcb7eb8bb616c170506312870b3bf15f3dbe37c, build date=2024-05-19T10:15:28Z, build source=binaryRelease, version=0.42.0, os=darwin, arch=amd64, git version=2.45.2
_Run `git --version` and paste the result here_
git version 2.45.2

**Comment by stefanhaller** [comment] 2024-06-12 12:06
Looks like a duplicate of #2563.

**Closed** 2024-06-12 12:09 UTC
Labels: bug
