### ISSUE TITLE
Lazygit exits on escaping the error modal window, instead of just closing the modal window

### ISSUE THREAD

**Issue by abeep** [jesseduffield/lazygit#886] opened 2020-07-05 18:54 UTC
**Describe the bug**
Lazygit exits on escaping the error modal window, instead of just closing the modal window
**To Reproduce**
1.  checkout the merge-request and then open lazygit
2. Lazygit would show a error "branch config: invalid merge" 
3. now try to close the error dialog using escape
4.  instead of closing the error dialog  lazygit exits
5. Lazygit interminently crashes see below

**Expected behavior**
The error dialog should close, Lazygit should not exit

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Macos- mojave 10.14.6 
 - Lazygit Version - commit=cf5cefb2d6bcfd0d403faca5875124eb9b0d7480, build date=2020-05-19T11:41:07Z, build source=binaryRelease, version=0.20.4, os=darwin, arch=amd64
 - The last commit id if you built project from sources (run : ```git-rev parse HEAD```)

**Additional context**
Lazygit crashes and show the below error

*errors.errorString unknown view
/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:301 (0x160b512)
/home/runner/work/lazygit/lazygit/pkg/gui/view_helpers.go:317 (0x168fcd4)
/home/runner/work/lazygit/lazygit/pkg/gui/confirmation_panel.go:90 (0x1696b84)
/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:483 (0x160c71c)
/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:465 (0x160c3c6)
/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:363 (0x1653eca)
/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:372 (0x16542d0)
/home/runner/work/lazygit/lazygit/pkg/app/app.go:158 (0x16a912b)
/home/runner/work/lazygit/lazygit/main.go:70 (0x16aa213)
/opt/hostedtoolcache/go/1.14.3/x64/src/runtime/proc.go:203 (0x1034c92)
/opt/hostedtoolcache/go/1.14.3/x64/src/runtime/asm_amd64.s:1373 (0x10621e1)
abhijitp-a01:cp-mgmt-app abhijitp$ lazygit
panic: unknown view

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).closeConfirmationPrompt(0xc000334820, 0xc00033c000, 0x1, 0xc000114000, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/gui/confirmation_panel.go:39 +0x182
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).createPopupPanel.func1(0xc00033c000, 0xc00057397c, 0x3)
	/home/runner/work/lazygit/lazygit/pkg/gui/confirmation_panel.go:109 +0x267
github.com/jesseduffield/gocui.(*Gui).consumeevents(0xc00033c000, 0x0, 0x0)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:483 +0x1ec
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc00033c000, 0xc000000003, 0xc000171c98)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:465 +0x216
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc000334820, 0x0, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:363 +0x63a
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc000334820, 0x0, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:372 +0x40
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc000265b20, 0xc0001bc800, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/app/app.go:158 +0x6b
main.main()
	/home/runner/work/lazygit/lazygit/main.go:70 +0x7f3

**Comment by jesseduffield** [comment] 2020-07-18 10:11
@abeep was this a once-off crash, or does this happen reliably? Is there a public repo that I could reproduce the error on?

**Comment by abeep** [comment] 2020-08-02 18:15
@jesseduffield it's easy to reproduce,  just checkout the merge-request in review from any branch  and open lazygit, it will crash

**Comment by jesseduffield** [comment] 2021-04-02 00:12
closing due to staleness

**Closed by jesseduffield** 2021-04-02 00:12 UTC
Labels: bug, dont-panic
