### ISSUE TITLE
lazygit: command not found

### ISSUE THREAD

**Issue by Vinzhuo** [jesseduffield/lazygit#6] opened 2018-08-05 02:53 UTC
Call  command: go get github.com/jesseduffield/lazygit
Execute lazygit command in iTerm2
prompt: -bash: lazygit: command not found

**Comment by andreimc** [comment] 2018-08-05 03:00
Do you have your $GOBIN in your $PATH

**Comment by Vinzhuo** [comment] 2018-08-05 06:53
It's work right well after set $GOBIN in my $PATH

**Comment by jesseduffield** [comment] 2018-08-05 08:38
@Vinzhuo does the issue remain after you close and re-open your terminal? The terminal session may not have the updated path set

**Comment by ssteiger** [comment] 2018-08-05 08:39
had the same problem
for future ref.: https://github.com/golang/go/wiki/SettingGOPATH#zsh

**Comment by jesseduffield** [comment] 2018-08-05 08:42
@ssteiger did following those linked steps resolve the issue for you?

**Comment by itsheng** [comment] 2018-08-05 15:46
I ended up adding these lines in my bash profile file ~/.bash_profile

export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN

Now it works and I am ready to remove SourceTree. Thank you! @jesseduffield

**Comment by kirinzer** [comment] 2018-08-06 07:48
@itsheng it's work for me, I add the same lines in my `.zshrc,` and reboot iTerm2, thx.

**Comment by ssteiger** [comment] 2018-08-06 08:08
Also important: when adding the lines @itsheng provided, add them at the **bottom** of the `.zshrc` file, not at the top

**Comment by jesseduffield** [comment] 2018-08-06 08:09
thanks guys! I'm closing this as it looks like the issue is resolved

**Closed by jesseduffield** 2018-08-06 08:09 UTC

**Comment by rand-kcs** [comment] 2025-01-20 08:13
it works for me as well to change from:

export PATH=$PATH:/usr/local/go/bin

to:

export GOBIN=~/go/bin
export PATH=$PATH:$GOBIN

**Comment by Vinzhuo** [comment] 2025-01-20 08:13
这是来自QQ邮箱自动回复邮件。
 
您好，您的邮件已收到，尽快给您回复。
