### ISSUE TITLE
Filenames with backslashes

### ISSUE THREAD

**Issue by RedBug312** [jesseduffield/lazygit#361] opened 2019-01-07 18:51 UTC
**Describe the bug**
Lazygit misbehaved when there's backslash `\` in filenames, its operations seemed to expand the backslashes for twice.

**To Reproduce**
```bash
$ ls
$ touch \\ \\\\
'\'  '\\'
$ lazygit
(remove file indicated as ?? "\\")
$ ls
'\'
```

**Expected behavior**
It's expected to delete file `\` and leave file `\\` still, since cursor is on the line of `?? "\\"`. In this case, the other line `?? "\\\\"` is removed however.

**Screenshots**
Before deletion to `\` the file
![default](https://user-images.githubusercontent.com/11537681/50786288-1546f900-12ee-11e9-990b-caee653f1215.png)

After deletion to `\` the file
![default](https://user-images.githubusercontent.com/11537681/50786305-21cb5180-12ee-11e9-8c1f-7de7efcd4cfa.png)

**Desktop (please complete the following information):**
 - OS: Xubuntu 18.04.1 LTS x86_64 
 - Lazygit Version: 0.5-1~ubuntu18.04.1

**Additional context**
I didn't build it from source because I'm not familiar to go language. This bug is merely confirmed on Ubuntu daily builds.

**Comment by KOREAN139** [comment] 2019-01-29 19:18
@jesseduffield 

this issue is caused by `OSCommand.Unquote` https://github.com/jesseduffield/lazygit/blob/3a607061a2303d9f45d308de652fbebe7300b43c/pkg/commands/os.go#L196

as this function only replace quotation mark as empty string, backslashes are printed doubled - since `git status --untracked-files=all --short` print filename **with quotation marks and leading backslash for escape characters** (ex. `ab\c"` is printed as `"ab\\c\""`)

not only double-printing backslashes, lazygit **panics when user select a file which contains quotation mark in its filename**

I think using `strconv.Unquote` can solve this issue

```go
/* 
 * since OSCommand.Unquote() is used only for unquote file names,
 * let message is file name given with `git status --untracked-files=all --short`
 */
func (c *OSCommand) Unquote(message string) string {
    /* unquote given file name */
    ret, err := strconv.Unquote(message)
    /* If there is no quotation mark - means no escape characters in file name */
    if err != nil {
      /* use original string */
      ret = message
    }
    return ret
}
```

If this patch looks ok for you, i'll make PR for this.

**Comment by jesseduffield** [comment] 2019-02-20 11:36
sorry for the late reply, that does look good to me :) I'll happily review your PR if you make one :)

**Comment by KOREAN139** [comment] 2019-03-11 13:03
@jesseduffield Sorry for late reply 😓  i'll make some PR soon for this issue, maybe within 2 weeks

**Comment by snipem** [comment] 2020-04-22 11:14
I saw something similar with `>` in filenames. The file was created by accident but still `git diff` is is failing and output is as follows:

![image](https://user-images.githubusercontent.com/985581/79975297-0e200c00-849b-11ea-9d56-07d8ccf57052.png)

**Comment by jesseduffield** [comment] 2021-03-13 00:22
this is fixed on latest master :)

**Closed by jesseduffield** 2021-03-13 00:22 UTC
Labels: bug, dont-panic
