### ISSUE TITLE
Crash when trying to open in `.git/` directory

### ISSUE THREAD

**Issue by jdujava** [jesseduffield/lazygit#3739] opened 2024-07-12 11:27 UTC
**Describe the bug**
Trying to open `lazygit` in the `.git/` directory of some repository results in a crash.

**To Reproduce**

1. `cd` into a `.git/` directory of some repository
2. try to launch `lazygit`
3. `lazygit` crashes with the following message:
```
2024/07/12 13:23:08 An error occurred! Please create an issue at: https://github.com/jesseduffield/lazygit/issues

*errors.errorString 'git -C /tmp/test/.git rev-parse --path-format=absolute --show-toplevel --absolute-git-dir --git-common-dir --is-bare-repository --show-superproject-working-tree' failed: fatal: this operation must be run in a work tree

/home/jonas/.cache/paru/clone/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/commands/git_commands/repo_paths.go:147 (0x9c0dd8)
/home/jonas/.cache/paru/clone/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/commands/git_commands/repo_paths.go:91 (0x9c05a8)
/home/jonas/.cache/paru/clone/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/commands/git_commands/repo_paths.go:83 (0x9c046c)
/home/jonas/.cache/paru/clone/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/app/app.go:123 (0xbcd3d9)
/home/jonas/.cache/paru/clone/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/app/app.go:45 (0xbccc78)
/home/jonas/.cache/paru/clone/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/app/entry_point.go:161 (0xbceef7)
/home/jonas/.cache/paru/clone/lazygit-git/src/src/github.com/jesseduffield/lazygit/main.go:23 (0xbd0858)
/usr/lib/go/src/runtime/internal/atomic/types.go:194 (0x441cdd)
    (*Uint32).Load: return Load(&u.value)
/usr/lib/go/src/runtime/asm_amd64.s:1695 (0x479e41)
    goexit: BYTE    $0x90   // NOP
```

**Expected behavior**
Lazygit shouldn't crash, but somehow (gracefully) handle this situation. 

**Version info:**
_Run `lazygit --version` and paste the result here_
`commit=e0377f2bc, build date=20240712.112152, build source=unknown, version=v0.42.0.e0377f2bc, os=linux, arch=amd64, git version=2.45.2`
_Run `git --version` and paste the result here_
`git version 2.45.2`

**Comment by mark2185** [comment] 2024-07-12 11:53
Duplicate of #3507 .

**Closed by mark2185** 2024-07-12 11:52 UTC
Labels: bug
