### ISSUE TITLE
lazygit-0.27.1 has broken prompt on git push (Shift+p) action

### ISSUE THREAD

**Issue by band-a-prend** [jesseduffield/lazygit#1231] opened 2021-04-07 20:49 UTC
The lazygit 0.27 and 0.27.1 have broken `git push` action by pressing shortcut `Shift+p`:
after pressing shortcut `Shift+p` the `Pushing ....\` popup is shown but no "https"/"ssh" prompts appear to ask credentials/passphrase even after long wait ~1 minute.

Both 0.27.x versions were built with Go 1.16.2 (Gentoo dev-lang/go-1.1.6.2).
The release of lazygit-0.26.1 isn't affected this issue.

**Comment by jesseduffield** [comment] 2021-04-08 14:41
@band-a-prend can you try v0.27.2?

**Comment by band-a-prend** [comment] 2021-04-08 19:09
Thank you! This issue is fixed in lazygit 0.27.2.

**Comment by joshgummersall** [comment] 2021-04-08 20:16
I noticed the same issue earlier today, just upgraded to 0.27.2, and the issue is resolved!

**Comment by jesseduffield** [comment] 2021-04-08 21:55
Sweet :) closing

**Closed by jesseduffield** 2021-04-08 21:55 UTC
Labels: bug

**Comment by fcomoreira1** [comment] 2021-04-09 00:56
When is version 0.27.2 going to be pushed to Copr?

**Comment by jesseduffield** [comment] 2021-04-12 08:40
I am actually not sure; I don't manage the Copr repo
