### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#3262] opened 2024-01-26 10:18 UTC
It's been a while since we cut a release (in no small part to me taking a break over the holiday period).

But we ought to cut one soon.

This issue is for deciding what should go into the next release so that we know what we're working towards.

Some issues/PRs I'd like to get into the next release:
* https://github.com/jesseduffield/lazygit/pull/3259
* https://github.com/jesseduffield/lazygit/issues/3260
* https://github.com/jesseduffield/lazygit/pull/3203 (pending further discussion)

* https://github.com/jesseduffield/lazygit/issues/3261
  - Something I've been thinking about is adding a release notes popup after the user updates their version, so that they can be warned about things like keybinding updates. This is especially prescient with the recent range select changes given that cherry pick keybindings have changed and I can imagine that being quite disruptive. 
  
What do we think about the above? And what other issues/PRs do people want in the release? @mark2185 @stefanhaller

**Comment by stefanhaller** [comment] 2024-01-26 10:36
I would love to include https://github.com/jesseduffield/lazygit/pull/3173. It's one of those things that I have been using in my fork for quite a while now, and wouldn't want to live without any more.

#3263 would be good to have because it's nicely complementary to the new 'i' command.

Also, https://github.com/jesseduffield/lazygit/pull/2936 is ready to be merged and only needs a final ok from you.

https://github.com/jesseduffield/lazygit/pull/3240 would be nice too (minor thing).

**Comment by stefanhaller** [comment] 2024-01-26 10:37
Oh, and #3258 since it's a regression from the last release.

**Comment by MariaSolOs** [comment] 2024-01-27 20:21
Is the list above for open issues only? Asking because I would love to see #2993 in the next release :)

**Comment by jwhitley** [comment] 2024-01-27 20:50
> Is the list above for open issues only? Asking because I would love to see #2993 in the next release :)

Already-merged stuff will go in, pretty much by definition. So the issues listed here are “things to land before the next release is cut”.

Anyhow, I’m game for pitching in on anything here. Feel free to point me at something.

Otherwise, I’ve been pounding on #3227, which may or may not be ready in time, but doesn’t seem vitally urgent. The repo_paths changes took ~10 minutes, but then I took to staring into the void of app-startup call sequence to see if I can also take out VerifyInGitRepo. (answer: yes, but then we’d have the first RepoPaths *much* earlier in time and what to do with it. Probably implies a “service” that manages retrieval and caching of RepoPaths, which are currently buried down under Gui.)

**Comment by jesseduffield** [comment] 2024-01-28 03:27
@jwhitley the only ticket above that's not already assigned is the release-notes one, does that interest you?

> Otherwise, I’ve been pounding on https://github.com/jesseduffield/lazygit/issues/3227, which may or may not be ready in time, but doesn’t seem vitally urgent. The repo_paths changes took ~10 minutes, but then I took to staring into the void of app-startup call sequence to see if I can also take out VerifyInGitRepo. (answer: yes, but then we’d have the first RepoPaths much earlier in time and what to do with it. Probably implies a “service” that manages retrieval and caching of RepoPaths, which are currently buried down under Gui.)

Nice, that sounds reasonable to me

**Comment by igor-ramazanov** [comment] 2024-03-21 23:38
@jesseduffield https://github.com/jesseduffield/lazygit/pull/2868 and https://github.com/jesseduffield/lazygit/pull/3222, please :pray:

**Closed** 2024-03-24 15:35 UTC
Labels: discussion
