### ISSUE TITLE
Installation via Homebrew

### ISSUE THREAD

**Issue by bartlomieju** [jesseduffield/lazygit#33] opened 2018-08-06 10:44 UTC
Is there any chance `lazygit` will be available via Homebrew? 

I tried installing via `go get` but I had to resolve some symlinks manually.

**Comment by Kriechi** [comment] 2018-08-06 11:16
duplicate of #14

**Comment by jesseduffield** [comment] 2018-08-06 11:37
as @Kriechi has pointed out this is a duplicate, so I'm going to close this. I've got a `Easy Installation` milestone that has a subtask of getting hooked up with homebrew, but I'm lacking in the knowledge of how to do that. Any help is much appreciated :)

**Closed by jesseduffield** 2018-08-06 11:37 UTC
