### ISSUE TITLE
branch config: invalid merge

### ISSUE THREAD

**Issue by ssbarnea** [jesseduffield/lazygit#501] opened 2019-08-23 10:32 UTC
**Describe the bug**
After installing lazygit from brew on MacOS, got a big error on its first execution

**To Reproduce**
``
$ lazygit                                                                                                                                                                  An error occurred! Please create an issue at https://github.com/jesseduffield/lazygit/issues

*errors.errorString branch config: invalid merge
/private/tmp/lazygit-20190625-82337-1uw655x/lazygit-0.8.1/src/github.com/jesseduffield/lazygit/main.go:55 (0x1836113)
/usr/local/Cellar/go/1.12.6/libexec/src/runtime/proc.go:200 (0x102f38c)
/usr/local/Cellar/go/1.12.6/libexec/src/runtime/asm_amd64.s:1337 (0x105a131)`
```

**Expected behavior**
Anything but not a crash.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Lazygit Version [commit=, build date=, build source=homebrew, version=0.8, os=darwin, arch=amd64]
 - The last commit id if you built project from sources (run : ```git-rev parse HEAD```)

**Additional context**
Add any other context about the problem here.

**Comment by arza-zara** [comment] 2019-09-19 18:08
I got this crash when some branch's upstream reference had been deleted.

To reproduce:
```
$ git config branch.test.merge refs/nonexistent
$ lazygit                                      
2019/09/19 20:53:36 An error occurred! Please create an issue at https://github.com/jesseduffield/lazygit/issues

*errors.errorString branch config: invalid merge
.../github.com/jesseduffield/lazygit/main.go:55 (0x5590b6bf7815)
        main: if errorMessage, known := app.KnownError(err); known {
/usr/lib/go/src/runtime/proc.go:203 (0x5590b63f7bf6)
        main: fn()
/usr/lib/go/src/runtime/asm_amd64.s:1357 (0x5590b64237a1)
        goexit: BYTE    $0x90   // NOP
```
(archlinux, commit=2ca029297ed29d2a6686a7a5ede89c20eb527ac6, build date=2019-09-19T14:14:45Z, build source=binaryRelease, version=0.8.1, os=linux, arch=amd64)

**Comment by jesseduffield** [comment] 2020-01-28 10:23
I've just encountered this myself. Turns out it's an issue with go-git, that occurs when we fetch remotes. I really do want to love go-git but it makes it hard for me. I think I'm going to make a fork of go-git that just doesn't care when that issue pops up because it shouldn't really cause issues reading the config, and testing locally it doesn't seem to lead to any other problems

**Comment by peppy** [comment] 2020-10-06 07:25
Just want to bump this as I can repro, and when it happens I can't close the error popup or interact with `lazygit` at all.

My reproduction is caused by doing a checkout using `hub`, but only seems to happen on very old branches. I'm not sure what makes it invalid, but here are the commands to reproduce in case you can be bothered:

```sh
git clone https://github.com/ppy/osu
cd osu
hub checkout https://github.com/ppy/osu/pull/3084
lazygit
```

An alternate simpler reproduction may be to just set the `merge = ` line of a branch in `.git/config` to something random/invalid:

![2020-10-06 16 24 05](https://user-images.githubusercontent.com/191335/95171162-7451de80-07f0-11eb-8215-0b4ef1b7ea1d.gif)

**Comment by jesseduffield** [comment] 2020-10-06 10:04
I've forked go-git so that it no longer validates upon unmarshalling a branch (I have no idea why it does that in the first place). Could somebody verify that https://github.com/jesseduffield/lazygit/pull/1037 resolves the issue on their end?

**Comment by peppy** [comment] 2020-10-06 11:45
Can confirm fixed 🥇

**Comment by jesseduffield** [comment] 2020-10-06 22:36
sweet, closing :)

**Closed by jesseduffield** 2020-10-06 22:36 UTC
Labels: bug, dependency, git-config
