### ISSUE TITLE
Commits pane is blank on version 0.24.2

### ISSUE THREAD

**Issue by carstengehling** [jesseduffield/lazygit#1140] opened 2021-01-13 05:18 UTC
After upgrading to version 0.24.2, the **commits** pane is blank. When selecting branch in the **Local branches** pane, I can clearly see the commit log, just not in the commits pane.

I use lazygit on Windows 10 WSL:

```
$ lazygit --version
commit=, build date=2020-12-24, build source=debian, version=0.24.2, os=linux, arch=amd64
```

![lazygit](https://user-images.githubusercontent.com/54675/104409601-e6ac2a80-5566-11eb-9c4c-e96eff34d1a1.png)

Let me know, if you need any more information. Thank you for a splendid piece of software!

**Comment by jesseduffield** [comment] 2021-01-14 10:10
hmm I actually have WSL setup on my PC. I'll give this a go there and see if I can replicate.

**Comment by jesseduffield** [comment] 2021-01-14 10:21
![lazygit-ubuntu](https://user-images.githubusercontent.com/8456633/104578074-5c6ede00-56ae-11eb-9252-8a1f0649635a.PNG)
I'm not able to reproduce the issue 
I have the exact same version/arch too:
```
lazygit --version
commit=, build date=2020-12-24, build source=debian, version=0.24.2, os=linux, arch=amd64
```

**Comment by jesseduffield** [comment] 2021-01-14 10:25
@carstengehling some questions that could help narrow down the cause:
1) do you know which version worked last? A git bisect might help get to the bottom of the issue i.e. cloning the lazygit repo and running `go run main.go` at the root of the repo to see how it behaves for a particular commit
2) does the error occur on all repos or just a specific repo?
3) does a list of commits appear if you select the reflog tab in the commits panel, or if you hit enter on a local branch?
4) what version of git do you have? I'm on 2.25.1

Let me know :)

**Comment by jesseduffield** [comment] 2021-01-14 10:33
Actually @carstengehling this might be the same problem that we're seeing in https://github.com/jesseduffield/lazygit/issues/1131. Are you using ssh-agent by any chance?

**Comment by carstengehling** [comment] 2021-01-15 05:11
Re 1: oh bugger... I must admit, that I didn't notice that ;-) But it is at least 6 months since I last did an `apt-get upgrade` , if that's any help.

Re 2: It happens on any repository. To make sure, that it is not something "outside" of lazygit's domain, I tried:
  - Repository within WSL's own filesystem. Eg. `~/somegitfolder`
  - Repository in Windows' filesystem. Eg. `/mnt/c/somegitfolder`
  - Repository cloned from a remote with ssh
  - Repository only initiated locally

Re 3: Reflog tab is also empty. Pressing enter on a branch in the "Local branches" comes up with "No commits"

Re 4: I am using git version 2.7.4 - which, now I come to think about it - is a rather old version compared to latest. But it is what I get on `apt-get upgrade` in WSL. I'll try to install a newer one and see if this has any effect.

 I don't use ssh-agent.

Another thing of interesting note: When I am on the Commits pane and press `R` to refresh, lazygit exits with this stacktrace:

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handleMidRebaseCommand(0xc420296000, 0xb0cd42, 0x6, 0x0, 0x3, 0xc420517b28)
        /build/lazygit-asRDrs/lazygit-0.24.2/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/pkg/gui/commits_panel.go:278 +0x19f
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handleRenameCommitEditor(0xc420296000, 0xc4202286c0, 0xc420183a20, 0x8f59dc, 0xb0d7c9)
        /build/lazygit-asRDrs/lazygit-0.24.2/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/pkg/gui/commits_panel.go:254 +0x7e
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).(github.com/jesseduffield/lazygit/pkg/gui.handleRenameCommitEditor)-fm(0xc4202286c0, 0xc420183a20, 0x1, 0xc4202d8830)
        /build/lazygit-asRDrs/lazygit-0.24.2/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/pkg/gui/keybindings.go:693 +0x3e
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybinding(0xc4202286c0, 0xc420183a20, 0xc420295680, 0xc420000180, 0xc420517a98, 0xc4200db440)
        /build/lazygit-asRDrs/lazygit-0.24.2/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:963 +0x3e
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc4202286c0, 0xc420183a20, 0xc4203b0360, 0x48, 0x58, 0xc4203b0360)
        /build/lazygit-asRDrs/lazygit-0.24.2/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:943 +0x1e9
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).onKey(0xc4202286c0, 0xc4203b0360, 0xae3260, 0xc4202efd01)
        /build/lazygit-asRDrs/lazygit-0.24.2/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:863 +0x2e2
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).handleEvent(0xc4202286c0, 0xc4203b0360, 0xc4205179b8, 0x0)
        /build/lazygit-asRDrs/lazygit-0.24.2/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:551 +0x48
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc4202286c0, 0xc420255bc0, 0x1)
        /build/lazygit-asRDrs/lazygit-0.24.2/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:499 +0x432
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc420296000, 0x0, 0x0)
        /build/lazygit-asRDrs/lazygit-0.24.2/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:504 +0x4ed
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc420296000, 0x0, 0xb10141)
        /build/lazygit-asRDrs/lazygit-0.24.2/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:517 +0x119
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc420207500, 0xc4201722d0, 0x0)
        /build/lazygit-asRDrs/lazygit-0.24.2/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/pkg/app/app.go:240 +0x74
main.main()
        /build/lazygit-asRDrs/lazygit-0.24.2/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/main.go:126 +0xa73
```

Hope this helps. I'll get back to you with results of git upgrade.

**Comment by carstengehling** [comment] 2021-01-15 05:20
**SOLVED**

@jesseduffield I just installed git version **2.29.0** from the official PPA. And this solved all problems! So thank you for asking for this detail - should have thought of it myself. 👍

**Comment by jesseduffield** [comment] 2021-01-15 08:19
Nice one! Do you recall which git version you were on previously? We try to support version 2.0 onwards, so if you were already on a 2.something git version, I might do some digging to see what caused the issue

**Comment by carstengehling** [comment] 2021-01-15 18:20
It was 2.7.0. But I can see, that lots of things have changed from that to 2.29.0, so maybe 2.0 compatible is a bit ambitious?

I'll try to downgrade incrementally until I get the error again. Then you'll know exactly from which Git version it currently works.

**Comment by lcc014** [comment] 2021-02-03 19:58
I had the same issue with git 2.7.4 and lazygit 0.23.x.  After I upgraded my git to 2.29.0 and lazygit to 0.24.2, commit window worked again with whole bunch of commits.

**Comment by xuerenxiang** [comment] 2021-02-11 03:55
it's my first time to use lazygit,and I am facing the same issue on version 0.24.1 and 0.24.1,even I upgraded to 0.20.4,it doesn't work.my git version is 2.9.0

**Comment by xuerenxiang** [comment] 2021-02-11 04:10
> it's my first time to use lazygit,and I am facing the same issue on version 0.24.2 and 0.24.1,even I upgraded to 0.20.4,it doesn't work.my git version is 2.9.0

I upgraded the git to 2.30.0 and the issue is solved~

**Comment by danielk333** [comment] 2021-05-25 14:35
I was facing the same problem with `git version 2.7.4` and lazygit 
```
commit=, build date=2021-03-14, build source=debian, version=0.26.1, os=linux, arch=amd64
```
It was fixed by upgrading to `git version 2.31.1`

**Comment by Ryooooooga** [comment] 2022-12-26 13:40
Fixed in https://github.com/jesseduffield/lazygit/pull/1529

**Comment by jesseduffield** [comment] 2023-02-12 06:31
Thanks @Ryooooooga !

**Closed by jesseduffield** 2023-02-12 06:31 UTC
Labels: bug
