### ISSUE TITLE
[Feature request] Add search functionality for Patch window

### ISSUE THREAD

**Issue by its0x08** [jesseduffield/lazygit#1032] opened 2020-10-01 07:00 UTC
**Is your feature request related to a problem? Please describe.**
I check huge commits and I want to be able to search inside a commit instead of endlessly scrolling and hoping to find what Im searching for !!

**Describe the solution you'd like**
I'd like to have "/" (slash search) functionality for the Patch window.

**Comment by jesseduffield** [comment] 2020-10-01 07:21
totally agree. I actually have no idea whether this would be easy or not, hopefully it's easy

**Comment by jesseduffield** [comment] 2020-10-01 23:09
@its0x08 I've got a PR up for this now, would you be able to give it a test? https://github.com/jesseduffield/lazygit/pull/1034. You can follow the instructions for manual install at https://github.com/jesseduffield/lazygit#manual

**Comment by its0x08** [comment] 2020-10-04 15:10
I installed the latest from git but dont se any difference :/

**Comment by jesseduffield** [comment] 2020-10-04 22:09
whoops I confused myself. The PR has the differences: https://github.com/jesseduffield/lazygit/pull/1034/files. You would need to check out that branch to see the differences

**Comment by its0x08** [comment] 2020-10-05 06:56
I did but still no search functionality ...
![screen](https://i.imgur.com/2LDlBZb.png)

**Comment by jesseduffield** [comment] 2020-10-05 07:38
it might be that `go install` has installed the binary to a directory that's not the first in your path. If you go `which lazygit` it will tell you where your current one is. I would try deleting that one and trying again.

**Comment by its0x08** [comment] 2020-10-05 08:26
I did it but nothing. :/

**Comment by jesseduffield** [comment] 2020-10-05 10:24
Not sure what the issue is there, at any rate I'll merge to master eventually and you'll be able to test on that

**Comment by jesseduffield** [comment] 2020-10-10 02:12
This is in v0.23.1, let me know if you have any other issues :) closing

**Closed by jesseduffield** 2020-10-10 02:12 UTC
Labels: enhancement

**Comment by krackout** [comment] 2024-10-06 18:22
Is this working? Trying to search something in patch window, I don't seem to be able to focus on it, in order to press `/` and search.
