### ISSUE TITLE
lazygit crashes when you try to stash changes

### ISSUE THREAD

**Issue by pawanjay176** [jesseduffield/lazygit#149] opened 2018-08-15 11:32 UTC
**Describe the bug**
stashing current changes causes application to crash with a `panic: runtime error: invalid memory address or nil pointer dereference`

**To Reproduce**
Stashing in any repository fails

**Screenshots**
![image](https://user-images.githubusercontent.com/9890508/44146374-e27e6368-a0ac-11e8-88cb-af9d88792509.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04

**Comment by jesseduffield** [comment] 2018-08-15 11:37
Hi @pawanjay176. What version of lazygit are you using? Would you be able to show a screenshot of what your application looks like before you commit (if it's not confidential?)

**Comment by pawanjay176** [comment] 2018-08-15 12:01
@jesseduffield `lazygit -v` gives me `commit=, build date=, version=unversioned~`
I installed using ubuntu package manager as mentioned in the README.
Here is a screenshot of a sample staged file
![image](https://user-images.githubusercontent.com/9890508/44147178-a2bff6e8-a0b0-11e8-976e-3c3531f63218.png)
Here is a screenshot of after I try stashing the changes
![image](https://user-images.githubusercontent.com/9890508/44147253-e6396cb0-a0b0-11e8-99f7-14cb8c9ffb8f.png)

**Comment by jesseduffield** [comment] 2018-08-15 12:13
I'm unable to replicate this locally. Have you obtained this via `go get` or some other means? Have you updated to the latest version? It may be that if you've used a linux installation method, a package could be missing. @dawidd6 are you able to troubleshoot this further?

**Comment by dawidd6** [comment] 2018-08-15 12:26
@pawanjay176 if you installed lazygit from PPA, then give us package version obtained with `dpkg -l lazygit`. I suppose you don't have latest build because recently i've implemented these ldflags needed to set these commit, date and version variables.

**Comment by pawanjay176** [comment] 2018-08-15 12:26
It works after updating to the latest version. Sorry for the trouble!
Cheers!

**Comment by dawidd6** [comment] 2018-08-15 12:33
No problem man. Just keep in mind that this daily PPA holds builds straight from master branch so it can be a little buggy.

I'm planning to create soon a new separate PPA with stable builds made from tags.

**Comment by jesseduffield** [comment] 2018-08-15 23:40
Glad to see the issue is resolved :) closing

**Closed by jesseduffield** 2018-08-15 23:40 UTC
