### ISSUE TITLE
[Windows] git diff is not shown using delta as pager in lazygit, but works fine in command line in terminal

### ISSUE THREAD

**Issue by hopezh** [jesseduffield/lazygit#2337] opened 2022-12-29 04:07 UTC
**Describe the bug**
As shown below, I can see the diff of a local git repo using `git diff` with [delta](https://github.com/dandavison/delta) as the pager in the terminal.

However, [lazygit](https://github.com/jesseduffield/lazygit) doesn't show this diff in the "`delta` way" although I have specified `delta` as its `pager`.

My `.gitconfig` and `config.yml` for `lazygit` are shown below.

Strangely, the same configuration works fine in `Mac OS` with `git diff` highlighted with `delta` in both `command-line` and `lazygit`...

May I ask what important steps I may have missed here?

Thanks.

**To Reproduce**
(As described above)

**Expected behavior**
(As described above)

**Screenshots**
running `git diff` in command-line:
![2022-12-28-15-13-49](https://user-images.githubusercontent.com/23435810/209901420-43c9ecf6-446f-4b69-95fa-7454890d6218.png)

`git diff` as shown in `lazygit`:
![2022-12-28-15-10-31](https://user-images.githubusercontent.com/23435810/209901482-758b7059-6c6a-4264-9b12-87c1e75bc04d.png)

**My git config file `~/.gitconfig`**
```
[user]
	name = USER
	email = USER@gmail.com
[core]
	pager = delta
[interactive]
    diffFilter = delta --color-only --features=interactive
[delta]
    navigate = true    
    light = false      
    side-by-side = true  
    line-numbers = true   
    features = decorations	 
[delta "interactive"]
    keep-plus-minus-markers = true
[delta "decorations"]
    commit-decoration-style = blue ol
    commit-style = raw
    file-style = omit
    hunk-header-decoration-style = blue box
    hunk-header-file-style = red
    hunk-header-line-number-style = "#067a00"
    hunk-header-style = file line-number syntax
[merge]
    conflictstyle = diff3
[diff]
    colorMoved = default
```

**My lazygit config file `~/AppData/Roaming/lazygit/config.yml`**
(I was directed to `~/AppData/Roaming` when I pasted `%APPDATA%` in File Explorer.)
```
git:
  paging:
    colorArg: never
    pager: delta --dark --paging=never 
    # pager: ydiff -p cat -s --wrap --width={{columnWidth}}   
    useConfig: false
```

**Version info:**
_Run `lazygit --version` and paste the result here_:
commit=d1a8b05401ccda1e52215203139a252eb3be3b79, build date=2022-11-14T09:22:31Z, build source=binaryRelease, version=0.36.0, os=windows, arch=amd64, git version=2.34.1.windows.1

_Run `git --version` and paste the result here_
git version 2.34.1.windows.1

**Additional context**
OS: Windows 11 Pro, 64bit, 22H2, build 22621.963

**Reference read**
#2300

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.

**Comment by aropele** [comment] 2023-01-03 08:45
Same probelm here, in the docs its written that custom pagers are not supported on Windows, however I think it would be quite usefull since delta allows quite a boost in productivity.

**Comment by Ryooooooga** [comment] 2023-01-04 12:52
duplicated of https://github.com/jesseduffield/lazygit/issues/1453

**Comment by mvolkmann** [comment] 2023-04-11 01:16
I'm begging for a solution to this one. I don't think I can use Lazygit if I can't get it to display side-by-side diffs. Has anyone successfully configured Lazygit to do this?

**Comment by hasansujon786** [comment] 2023-04-15 11:27
Having same issue :(

**Comment by mvolkmann** [comment] 2023-05-10 01:27
I FINALLY got side-by-side diffs to work! See my writeup at https://mvolkmann.github.io/blog/topics/#/blog/neovim/. Click "16. Lazygit" in the table of contents at the top. My instructions are specific to macOS.

**Comment by hopezh** [comment] 2023-05-10 05:10
> I FINALLY got side-by-side diffs to work! See my writeup at https://mvolkmann.github.io/blog/topics/#/blog/neovim/. Click "16. Lazygit" in the table of contents at the top. My instructions are specific to macOS.

Thanks. Unfortunately, the issue I reported, and echoed by others, are for Windows system, specifically... There's no solution, so far, as it seems...

**Comment by CharlesChiuGit** [comment] 2023-05-18 08:23
My same config works on linux but not windows too. In linux, I can utilize `delta` as git parser perfectly.

**Comment by pidgeon777** [comment] 2023-05-22 19:50
I also have the same issue, running `delta` and `lazygit` on Windows 10 x64. Any bugfix @jesseduffield ?

**Comment by adrivn** [comment] 2023-06-07 09:20
Same here. Using `delta` as custom pager works as intended in the terminal but does not when using/invoking a `lazygit` instance.

Using Windows 10 x64 as well.

**Comment by jesseduffield** [comment] 2023-06-07 22:56
Closing as a duplicate of https://github.com/jesseduffield/lazygit/pull/2715

Believe me, I want windows to work just as well as osx/linux but we have a dependency with a windows-compatibility [PR](https://github.com/creack/pty/pull/155) that's stuck in limbo so there's not much we can do until that's merged

**Closed by jesseduffield** 2023-06-07 22:56 UTC
Labels: bug

**Comment by hopezh** [comment] 2023-06-08 02:44
Understood. This is not a critical issue. I'm learning and enjoying `lazygit` everyday. Thank you very much.

**Comment by CharlesChiuGit** [comment] 2023-06-08 02:48
> Closing as a duplicate of #2715
> 
> Believe me, I want windows to work just as well as osx/linux but we have a dependency with a windows-compatibility [PR](https://github.com/creack/pty/pull/155) that's stuck in limbo so there's not much we can do until that's merged

Got it! Thanks for the reply.

**Comment by GitMurf** [comment] 2024-09-15 22:24
In case others stumble upon this issue, above it was mentioned a duplicate of an older PR. Here is the most up to date open issue to follow: #1453
