### ISSUE TITLE
Faster diff mode navigation

### ISSUE THREAD

**Issue by nagy135** [jesseduffield/lazygit#942] opened 2020-08-19 13:08 UTC
I just recently discovered diff mode and I see how this would be amazing to my lazygit workflow. I would really like to use this feature but I dont find it very usefull to scroll through the differences. I mean J/K scrolls me up and down but that isnt really usefull in large branch differences. I think this would be very usefull feature if I could just see overview of files that changed (maybe with +/- changes like on gitlab where compare shows repo tree with only changed files and their parent directories) or at least have option to jump to next file in that diff output window. In state I see it now it doesnt really feel usefull in real life scenario. If I m not seeing something obvious, please, let me know...I might be just lost in many features it provides :)

**Comment by jesseduffield** [comment] 2020-08-19 22:05
Closing as a duplicate of https://github.com/jesseduffield/lazygit/issues/942

Don't worry though, I'm doing a big refactor now so that I can start on this feature!

**Closed by jesseduffield** 2020-08-19 22:05 UTC
Labels: enhancement

**Comment by nagy135** [comment] 2020-08-20 10:24
cant wait! :) good luck
