### ISSUE TITLE
When commiting files lazygit exits

### ISSUE THREAD

**Issue by Turmaxx** [jesseduffield/lazygit#2986] opened 2023-09-04 06:24 UTC
**Describe the bug**
When you press enter to commit your files, lazygit prompts you to return to lazygit. 

**To Reproduce**

1. Stage your files
2. Add a commit message and commit them
3. press enter

**Expected behavior**
stay in lazygit's terminal UI, until prompting lazygit to leave by pressing q

**Screenshots**

**Version info:**
lazygit and git  version
```
commit=, build date=, build source=nix, version=0.38.2, os=linux, arch=amd64, git version=2.40.1
```

**Additional context**
I'd add a video or screenshots to show what it looks like. also I have tried uninstalling and installing it and same behavior,
I've also tried installing it through home-manager
 
Platform: Linux
OS: NixOS
Package Repo: [nixpkgs](https://search.nixos.org/packages?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=lazygit)

**Comment by mark2185** [comment] 2023-09-04 06:50
> I've also tried installing it through home-manager

Does that mean the bug also happens on `v0.40.2`?

> When you press enter to commit your files, lazygit prompts you to return to lazygit.

How does your `~/.gitconfig` look regarding `commit` options?

**Comment by Turmaxx** [comment] 2023-09-04 06:55
> Does that mean the bug also happens on v0.40.2?

I haven't updated my flake, so i''ll try doing that.

> How does your `~/.gitconfig` look regarding `commit` options?
```
[commit]
        gpgSign = true
```

**Comment by mark2185** [comment] 2023-09-05 13:43
Does it also happen when `gpgSign` is disabled?

**Comment by Turmaxx** [comment] 2023-09-05 13:53
same thing happens with `gpgSign` disabled.
I honestly don't know what is causing the bug. 
I have been using lazygit for about couple of years now, and haven't experienced any problems in relation to this.

**Comment by mark2185** [comment] 2023-09-05 14:00
Could you try different terminal emulators? E.g. kitty, alacritty, terminator, xterm?

Does it happen in more repositories than one?

**Comment by mark2185** [comment] 2023-09-25 10:39
Could you post your `lazygit` config, i.e. `config.yml`?

**Comment by Turmaxx** [comment] 2023-09-25 12:14
the `config.yaml` is empty.

**Comment by mark2185** [comment] 2023-09-25 12:28
Just to confirm,  you're committing using `c`, i.e. the internal editor which brings up a popup where you write your commit message, not `C` which delegates to `vim` or something else?

**Comment by Turmaxx** [comment] 2023-10-01 10:02
yes, I am using `c` then pop up comes up.

**Comment by cpoile** [comment] 2023-11-03 19:59
I see the exact same thing:
1. press c to commit, type in the msg in the commit popup, press enter
2. lazygit quits the UI, shows the terminal, performs the git commit command, then says `Press enter to return to lazygit` (exactly the same as https://github.com/jesseduffield/lazygit/issues/2986#issuecomment-1706713792 )

I was very surprised the first few times this happened -- I thought it crashed.

I think it would be better UX if the commit action and feedback appeared in the `Comman log` at the bottom of the screen and the UI stayed focused. 

Otherwise, thanks for a great utility @jesseduffield and contributers!

**Comment by mark2185** [comment] 2023-11-03 20:12
> I think it would be better UX if the commit action and feedback appeared in the Comman log at the bottom of the screen and the UI stayed focused.

Well that is what's supposed to happen, this smells like a bug.

Does this happen every time you try to commit? Would you maybe be willing to bisect `lazygit` to see when this started happening? I ask only because I can't reproduce.

**Comment by stefanhaller** [comment] 2023-11-05 16:42
Lazygit suspends itself to the background if you have `commit.gpgsign` set to true in your git config. It does this because you might have to type in a password, so we need to be in the console when that happens. @Turmaxx claimed above that this still happens when disabling the `commit.gpgsign` config, but honestly I don't believe that; maybe you didn't quit and restart lazygit when you turned off the option? Lazygit caches git configs in memory for performance, so you need to quit and restart for changes to take effect.

If you want to keep `commit.gpgsign` on, and you are sure that you won't have to type a password (I'm not familiar with gpg signing, so I don't know under what conditions that would be the case), then you can set the lazygit config `git.overrideGpg` to true to disable the suspending.

**Comment by stefanhaller** [comment] 2023-11-08 13:24
@Turmaxx @cpoile Could you please verify/confirm this? I'd like to close this as "works as expected".

**Comment by cpoile** [comment] 2023-11-09 13:58
Setting `git.overrideGpg` to true works like a charm, problem solved. Thank you @stefanhaller and @mark2185 !

**Comment by stefanhaller** [comment] 2023-11-19 16:06
Since there was no feedback from @Turmaxx I can't be sure if the problem is solved for them too, but I'll assume it is, so I'm closing this. Feel free to reopen if there are still unsolved problems related to this.

**Closed by stefanhaller** 2023-11-19 16:06 UTC
Labels: bug
