### ISSUE TITLE
Edit a file in the current line when on diff view - on press 'e'

### ISSUE THREAD

**Issue by jdavid1385** [jesseduffield/lazygit#807] opened 2020-04-22 09:14 UTC
**Is your feature request related to a problem? Please describe.**
In `tig` when I press `e` on the diff view, it takes me to the file in the current line I am sitting on. That is not the case in lazygit.

**Describe the solution you'd like**
I would like the editor to open in the exact current line I triggered the edition.

**Comment by luckscx** [comment] 2021-01-09 03:40
This feature is quite useful.i  vote for it.

**Comment by jdavid1385** [comment] 2021-01-09 22:47
> @jdavid1385 interesting, do you use `vim` as your editor? I know that we can pass `+<line number>` to the vim command, but that does not extend to other programs.

Hey, sorry for the late reply, had almost forget about this request. Yes, I use vim as my editor. I guess, of being implemented, that'd be only for vim if the case is of open-at-line being available only on it. Thanks for considering its implementation.

**Comment by jesseduffield** [comment] 2021-04-06 22:51
closing as a duplicate of https://github.com/jesseduffield/lazygit/issues/807 (even though I'm aware this one came first). We're going to allow user-specified commands for opening files at a particular line

**Closed by jesseduffield** 2021-04-06 22:51 UTC
Labels: enhancement, usability
