### ISSUE TITLE
`go install` leaves the binary "unversioned"

### ISSUE THREAD

**Issue by jbrains** [jesseduffield/lazygit#1439] opened 2021-08-16 12:16 UTC
When I use `go install` to install lazygit, the resulting binary is "unversioned" according to `lazygit --version`. I presume that we'd _like_ to have some build metadata available, especially to help with debugging/diagnosing defects.

1. Clone the lazygit source.
2. `go install`
3. `$HOME/.go/bin/lazygit --version`

I get `commit=, build date=, build source=unknown, version=unversioned, os=linux, arch=amd64`, but I expect at least the commit hash in this metadata.

**Desktop (please complete the following information):**
 - Pop!_OS 21.04
 - The last commit id if you built project from sources: 6c415d13413f18c0b3846539c3fa4646b6c896a3

**Comment by mjarkk** [comment] 2021-08-16 14:37
This might sound wired but this somewhat intended behavior.
These values are explicitly set in the CD, see [/.goreleaser.yml#18](https://github.com/jesseduffield/lazygit/blob/master/.goreleaser.yml#L18) for how we do that.

But your point is still valid maybe we should have some go code generator that sets these values automatically.

**Comment by jbrains** [comment] 2021-08-18 18:59
Not weird, merely unexpected.

Should I use `goreleaser`, then, to build locally from source? (I just happened to learn yesterday what the sentence even means.)

**Comment by jesseduffield** [comment] 2021-08-25 12:34
If there is a way to bake in the current tag or commit hash via `go install` I would definitely do that, but I don't actually know how haha

**Comment by jesseduffield** [comment] 2021-08-25 12:36
This guide shows a way to do it, however it would require us providing a shell script that handles the different variables https://blog.alexellis.io/inject-build-time-vars-golang/

**Comment by jesseduffield** [comment] 2022-01-18 22:59
I think Go might actually support this natively now: https://github.com/golang/go/issues/37475

**Comment by jbrains** [comment] 2022-01-19 18:16
Excellent! Since I build from source, I find it helpful be able to confirm that I indeed built the expected version of lazygit and installed it to the right place without checking file timestamps.

**Comment by jesseduffield** [comment] 2022-08-01 10:25
This is fixed in https://github.com/jesseduffield/lazygit/pull/2076

While I have the chance @jbrains I wanna say I've come across your blog posts on testing and they are phenomenal. Thanks for writing them!

**Closed** 2022-08-01 10:26 UTC
Labels: bug

**Comment by jbrains** [comment] 2022-08-01 13:44
I have the fix! Thank you.
