### ISSUE TITLE
Lazygit should just pass commands to git instead of trying to do its own thing

### ISSUE THREAD

**Issue by Rizhiy** [jesseduffield/lazygit#1180] opened 2021-03-04 01:59 UTC
**Is your feature request related to a problem? Please describe.**
Basically lazygit doesn't respect my .gitconfig and other settings.
For example: I have pull with rebase setup (`[pull] rebase = true`), but when I pull using lazygit it creates a merge. I have similar problems with switching branches, checking out commits and other things.

**Describe the solution you'd like**
Instead of running whatever custom code you have, just invoke git commands in the terminal with appropriate arguments.

**Describe alternatives you've considered**
I could make separate issues for each problem here, but that is like treating the symptoms instead of the cause.

**Additional context**
N/A

**Comment by band-a-prend** [comment] 2021-04-10 18:36
This issue is duplicate of https://github.com/jesseduffield/lazygit/issues/1151

**Comment by Rizhiy** [comment] 2021-04-10 19:14
Not exactly, lazygit also does some strange stuff on remote branch checkout.

If I run `git` checkout remote-branch`, git will fetch the remote branch, checkout it and set upstream to remote.
If I try to checkout remote branch with lazygit, it gives me an option to create a branch with custom name, but I still need to set upstream afterwards.

**Comment by eruizc-dev** [comment] 2021-04-11 01:57
I think this is worth clarifying, @jesseduffield could you explain why this isn't the current behavior and if there's any plan or chances into changing this? I see this very confusing, some global git configurations are respected (like default branch name) and some others are not.
I don't mind how it's done really as long as it does the same, but the question I wanna make is: wouldn't be easier to pass commands to git rather than whatever it's doing rn and constantly maintaining it to make sure it does the same?
I haven't looked at the codebase yet, I'm not that familiar with golang but I'm learning. If your agree with this change, I'd be happy to help with the changes needed.

**Comment by jesseduffield** [comment] 2021-04-11 05:12
@eruizc-dev as you might have suspected: there is really no good reason :) We actually do already just run git commands directly (as opposed to through some kind of api): I assume it wouldn't be hard to run the commands in such a way where the config is honoured.

There will be times however where certain flags will need to be passed or lazygit will simply break, but I think an audit of where we can just use the user's config would be good.

I'm soon to merge a PR which logs which commands are actually run (the ones that are mutative at least), and that should give a better idea of where we're passing weird flags.

Lemme know your thoughts :)

**Comment by Rizhiy** [comment] 2021-04-11 16:37
I have checked the remote branch behaviour and if the branch name matches then it works properly.
I guess my request regarding remote branches would be to default to a plain branch name, unless there is conflict.

In my experience working with multiple remotes is quite rare and it is better to have defaults for most probable paths. Maybe that can be a config option.

**Comment by eruizc-dev** [comment] 2021-04-12 00:38
I've been looking a bit deeper into the codebase and I can see what @jesseduffield mentions. I'd say there *is* an issue here that should be addressed, I've already seen many people complain about things like this.
Now that I know that it's not a general rule for lazygit to ignore gitconfig and it affects each command independently I'd like to try and work on the `git pull` fix during this week. Here's my take on the solution:

The pull mode it's currently specified in the [config file](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#default):
```yml
git:
  pull:
    mode: 'merge' # one of 'merge' | 'rebase' | 'ff-only'
```
I don't think these commands should be configurable since they're so simple and don't have anything to do with the UI or QOL. Either:
 - Remove this option completely.
 - Add an 'auto' option that uses git config instead, and make this the default value.

I can start working on this as soon as you give me the green light :smiley:

**Comment by jesseduffield** [comment] 2021-04-12 02:03
@eruizc-dev yep that sounds reasonable. My only concern is that currently it's doing the pull in a kinda weird way so that we can make of lazygit's visual representation of mid-way interactive rebases i.e. it actually does an interactive rebase so that if there's failures halfway through you can see where you're up to which to my knowledge is only possible with an interactive rebase. But I'm happy to lose that functionality if it means more peace of mind for users.

**Comment by eruizc-dev** [comment] 2021-04-13 00:22
@jesseduffield sorry for the late response but I wanted to investigate more about that merge and rebase feature I've never used before. I don't want Lazygit to lose any of its functionality but rather replace the hardcoded `pull.mode = merge` in the default config with whatever the user configured in its `.gitconfig` file.

I'm currently working on a solution that doesn't affect the interactive merge/rebase and follows this rule as I previously mentioned [here](https://github.com/jesseduffield/lazygit/issues/1151#issuecomment-786928070):

lazygit config -> git config-> default to merge

I will be soon submitting a PR

**Comment by jesseduffield** [comment] 2021-10-23 01:28
As of https://github.com/jesseduffield/lazygit/pull/1532 I've removed the lazygit config around pull mode and now we leave it completely up to git to work out what to do. I personally use `pull.rebase = interactive` so that I can see which commits are yet to be rebased when doing a pull, but if you have something else configured that will work fine too.

I've also removed the `--follow-tags` arg from the push command, again just letting git decide whether to follow tags based on the git config. As such I'll close this issue but let me know if you have any other issues

**Closed by jesseduffield** 2021-10-23 01:28 UTC
Labels: enhancement
