### ISSUE TITLE
Deleting a branch with its upstream

### ISSUE THREAD

**Issue by oereneli** [jesseduffield/lazygit#2321] opened 2022-12-19 13:17 UTC
It would be great that when I deleted a branch locally, lazygit prompts to ask if I want to delete remote upstream branch also. This works in Intellij's internal git manager. Another approach also might be instead of `d` we can use `D` to delete the branch with its upstream.

**Comment by mark2185** [comment] 2022-12-19 13:23
Duplicate of #2157 .

Do please add your suggestions there :)

**Closed by mark2185** 2022-12-19 13:23 UTC
Labels: enhancement

**Comment by oereneli** [comment] 2022-12-19 13:25
Sorry I didn't see that 👍
