### ISSUE TITLE
Program Exits When Pressing SHIFT-TAB, SHIFT-PgUp, or SHIFT-PgDn

### ISSUE THREAD

**Issue by ewhac** [jesseduffield/lazygit#1203] opened 2021-03-28 00:37 UTC
**Describe the bug**
The program exits whenever I press the key combos SHIFT-TAB, SHIFT-PageUp, or SHIFT-PageDown.

**To Reproduce**
1. Launch lazygit.
2. Press any of the above key combos.
3. Program exits immediately.

**Expected behavior**
Either nothing, or a notice/error message reporting an unrecognized keystroke.

**Desktop (please complete the following information):**
 - OS: Linux (Debian Sid, x86_64)
 - Lazygit Version 0.26.1 (using Ubuntu 18.04 package)

**Comment by jesseduffield** [comment] 2021-03-28 00:52
I believe this is fixed in the `tcell-again` branch but I still need to get back to that and fix some bugs before merging it. Once that branch is merged, you'll be able to use tab and shift-tab to cycle the side views!

**Comment by jesseduffield** [comment] 2021-04-02 11:40
@ewhac could you check if the issue is resolved on the `tcell-again` branch?

**Comment by jesseduffield** [comment] 2021-04-06 09:34
Should be fixed on master now. Let me know if it's not :)

**Closed** 2021-04-06 14:09 UTC
Labels: bug
