### ISSUE TITLE
[Issue] `pager` setting not respected in lazygit configuration

### ISSUE THREAD

**Issue by pidgeon777** [jesseduffield/lazygit#3971] opened 2024-10-07 10:00 UTC
**Describe the bug**
It seems that the `pager` setting is not respected when using `lazygit`.

**To Reproduce**

1. Edit the `config.yml` file to include the following:

```yaml
git:
  paging:
    colorArg: always
    pager: delta --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
```

2. Open a random commit in lazygit.

**Expected behavior**
I would expect lazygit to use `delta` as the pager, showing its output in the right panel.

**Screenshots**

**Version info:**
_Run `lazygit --version` and paste the result here_

```log
commit=611fabde11d24d9acc71ee26077b9a1101f59f27, build date=2024-09-18T10:56:10Z, build source=binaryRelease, version=0.44.1, os=windows, arch=amd64, git version=2.46.2.windows.1
```

_Run `git --version` and paste the result here_

```log
git version 2.46.2.windows.1
```

**Additional context**

Output of `lazygit --logs` when doing the test with `lazygit --debug`:

```log
Oct  7 11:55:15 |INFO| Heap memory in use: 5.7 MB
Oct  7 11:55:15 |INFO| refreshed merge conflicts in 0s
Oct  7 11:55:15 |DEBU| using cache for key status.showUntrackedFiles
Oct  7 11:55:15 |DEBU| RunCommand command="git status --untracked-files=all --porcelain -z --find-renames=50%"
Oct  7 11:55:15 |INFO| git status --untracked-files=all --porcelain -z --find-renames=50% (53.1297ms)
Oct  7 11:55:15 |INFO| refreshed files in 61.2704ms
Oct  7 11:55:15 |INFO| Refresh took 61.2704ms
Oct  7 11:55:15 |INFO| postRefreshUpdate for submodules took 0s
Oct  7 11:55:15 |INFO| postRefreshUpdate for files took 7.3677ms
Oct  7 11:55:15 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim diff --no-ext-diff --submodule --unified=3 --color=always --find-renames=50% -- lua/lazyvim/util/lazygit.lua"
Oct  7 11:55:25 |INFO| refreshing the following scopes in sync mode: files
Oct  7 11:55:25 |INFO| refreshed merge conflicts in 0s
Oct  7 11:55:25 |DEBU| using cache for key status.showUntrackedFiles
Oct  7 11:55:25 |DEBU| RunCommand command="git status --untracked-files=all --porcelain -z --find-renames=50%"
Oct  7 11:55:25 |INFO| git status --untracked-files=all --porcelain -z --find-renames=50% (54.0118ms)
Oct  7 11:55:25 |INFO| refreshed files in 63.3751ms
Oct  7 11:55:25 |INFO| Refresh took 63.3751ms
Oct  7 11:55:25 |INFO| postRefreshUpdate for submodules took 0s
Oct  7 11:55:25 |INFO| postRefreshUpdate for files took 7.7761ms
Oct  7 11:55:25 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim diff --no-ext-diff --submodule --unified=3 --color=always --find-renames=50% -- lua/lazyvim/util/lazygit.lua"
Oct  7 11:55:35 |INFO| refreshing the following scopes in sync mode: files
Oct  7 11:55:35 |INFO| refreshed merge conflicts in 0s
Oct  7 11:55:35 |DEBU| using cache for key status.showUntrackedFiles
Oct  7 11:55:35 |DEBU| RunCommand command="git status --untracked-files=all --porcelain -z --find-renames=50%"
Oct  7 11:55:35 |INFO| git status --untracked-files=all --porcelain -z --find-renames=50% (56.665ms)
Oct  7 11:55:35 |INFO| refreshed files in 64.7396ms
Oct  7 11:55:35 |INFO| Refresh took 64.7396ms
Oct  7 11:55:35 |INFO| postRefreshUpdate for submodules took 0s
Oct  7 11:55:35 |INFO| postRefreshUpdate for files took 7.7544ms
Oct  7 11:55:35 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim diff --no-ext-diff --submodule --unified=3 --color=always --find-renames=50% -- lua/lazyvim/util/lazygit.lua"
Oct  7 11:55:37 |INFO| git log HEAD --topo-order --oneline --pretty=format:%H%x00%at%x00%aN%x00%ae%x00%D%x00%p%x00%m%x00%s --abbrev=40 -300 --no-show-signature -- (74.9928ms)
Oct  7 11:55:37 |DEBU| using cache for key rebase.updateRefs
Oct  7 11:55:37 |INFO| postRefreshUpdate for commits took 0s
Oct  7 11:55:37 |DEBU| RunCommand command="git for-each-ref --sort=-committerdate --format=%(HEAD)%00%(refname:short)%00%(upstream:short)%00%(upstream:track)%00%(push:track)%00%(subject)%00%(objectname)%00%(committerdate:unix) refs/heads"
Oct  7 11:55:37 |INFO| git for-each-ref --sort=-committerdate --format=%(HEAD)%00%(refname:short)%00%(upstream:short)%00%(upstream:track)%00%(push:track)%00%(subject)%00%(objectname)%00%(committerdate:unix) refs/heads (61.0382ms)
Oct  7 11:55:37 |DEBU| RunCommand command="git symbolic-ref --short HEAD"
Oct  7 11:55:37 |ERRO| fatal: ref HEAD is not a symbolic ref
 command="git symbolic-ref --short HEAD"
Oct  7 11:55:37 |INFO| git symbolic-ref --short HEAD (42.2946ms)
Oct  7 11:55:37 |DEBU| RunCommand command="git branch --points-at=HEAD --format=%(HEAD)%00%(objectname)%00%(refname)"
Oct  7 11:55:37 |INFO| git branch --points-at=HEAD --format=%(HEAD)%00%(objectname)%00%(refname) (43.8483ms)
Oct  7 11:55:37 |DEBU| RunCommand command="git worktree list --porcelain"
Oct  7 11:55:37 |INFO| git worktree list --porcelain (40.7296ms)
Oct  7 11:55:37 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim rev-parse --path-format=absolute --absolute-git-dir"
Oct  7 11:55:37 |INFO| git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim rev-parse --path-format=absolute --absolute-git-dir (40.4184ms)
Oct  7 11:55:37 |INFO| postRefreshUpdate for worktrees took 0s
Oct  7 11:55:37 |INFO| postRefreshUpdate for localBranches took 0s
Oct  7 11:55:37 |DEBU| using cache for key rebase.updateRefs
Oct  7 11:55:38 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim diff --no-ext-diff --submodule --unified=3 --color=always --find-renames=50% -- lua/lazyvim/util"
Oct  7 11:55:38 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim diff --no-ext-diff --submodule --unified=3 --color=always --find-renames=50% -- lua/lazyvim/util/lazygit.lua"
Oct  7 11:55:38 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim diff --no-ext-diff --submodule --unified=3 --color=always --find-renames=50% -- lua/lazyvim/util"
Oct  7 11:55:39 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim diff --no-ext-diff --submodule --unified=3 --color=always --find-renames=50% -- lua/lazyvim/util/lazygit.lua"
Oct  7 11:55:41 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim diff --no-ext-diff --submodule --unified=3 --color=always --find-renames=50% -- lua/lazyvim/util/lazygit.lua"
Oct  7 11:55:43 |DEBU| RunCommand command="git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium a1c3ec4cd43fe61e3b614237a46ac92771191c81 --"
Oct  7 11:55:44 |DEBU| RunCommand command="git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium refs/heads/main --"
Oct  7 11:55:44 |ERRO| Unexpected error when running cmd task: exit status 1; Failed command: C:\Users\<USERNAME>\scoop\shims\git.exe [git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium a1c3ec4cd43fe61e3b614237a46ac92771191c81 --]
Oct  7 11:55:45 |DEBU| RunCommand command="git status --untracked-files=all --porcelain -z --find-renames=50%"
Oct  7 11:55:45 |INFO| git status --untracked-files=all --porcelain -z --find-renames=50% (53.1995ms)
Oct  7 11:55:45 |INFO| refreshed files in 60.9105ms
Oct  7 11:55:45 |INFO| Refresh took 60.9105ms
Oct  7 11:55:45 |INFO| postRefreshUpdate for submodules took 506.8µs
Oct  7 11:55:45 |INFO| postRefreshUpdate for files took 0s
Oct  7 11:55:45 |DEBU| using cache for key rebase.updateRefs
Oct  7 11:55:45 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim -c diff.noprefix=false show --no-ext-diff --submodule --color=always --unified=3 --stat --decorate -p 39ca76c9607a7d92aff5b97c50b7ccbf1b2d46b6 --find-renames=50%"
Oct  7 11:55:46 |DEBU| using cache for key rebase.updateRefs
Oct  7 11:55:46 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim -c diff.noprefix=false show --no-ext-diff --submodule --color=always --unified=3 --stat --decorate -p 627215a72b7744973a778722724d07eccefa0c79 --find-renames=50%"
Oct  7 11:55:47 |DEBU| using cache for key rebase.updateRefs
Oct  7 11:55:47 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim -c diff.noprefix=false show --no-ext-diff --submodule --color=always --unified=3 --stat --decorate -p 39ca76c9607a7d92aff5b97c50b7ccbf1b2d46b6 --find-renames=50%"
Oct  7 11:55:48 |DEBU| using cache for key rebase.updateRefs
Oct  7 11:55:48 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim -c diff.noprefix=false show --no-ext-diff --submodule --color=always --unified=3 --stat --decorate -p a1c3ec4cd43fe61e3b614237a46ac92771191c81 --find-renames=50%"
Oct  7 11:55:49 |DEBU| using cache for key rebase.updateRefs
Oct  7 11:55:49 |DEBU| using cache for key rebase.updateRefs
Oct  7 11:55:49 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim -c diff.noprefix=false show --no-ext-diff --submodule --color=always --unified=3 --stat --decorate -p 39ca76c9607a7d92aff5b97c50b7ccbf1b2d46b6 --find-renames=50%"
Oct  7 11:55:50 |DEBU| using cache for key rebase.updateRefs
Oct  7 11:55:50 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim -c diff.noprefix=false show --no-ext-diff --submodule --color=always --unified=3 --stat --decorate -p 627215a72b7744973a778722724d07eccefa0c79 --find-renames=50%"
Oct  7 11:55:50 |DEBU| using cache for key rebase.updateRefs
Oct  7 11:55:50 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim -c diff.noprefix=false show --no-ext-diff --submodule --color=always --unified=3 --stat --decorate -p 6dcd9794b1819965eb4f3dca70a1eb3c463de3cf --find-renames=50%"
Oct  7 11:55:50 |DEBU| using cache for key rebase.updateRefs
Oct  7 11:55:50 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim -c diff.noprefix=false show --no-ext-diff --submodule --color=always --unified=3 --stat --decorate -p 86d4f14bc89b2174cadde93a4f49fc83a01df642 --find-renames=50%"
Oct  7 11:55:50 |DEBU| using cache for key rebase.updateRefs
Oct  7 11:55:50 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim -c diff.noprefix=false show --no-ext-diff --submodule --color=always --unified=3 --stat --decorate -p d67be9a9fb7b5ad7d450ebd97a8dbb34415bfdb2 --find-renames=50%"
Oct  7 11:55:51 |DEBU| using cache for key rebase.updateRefs
Oct  7 11:55:51 |DEBU| RunCommand command="git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium refs/heads/main --"
Oct  7 11:55:51 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim diff --no-ext-diff --submodule --unified=3 --color=always --find-renames=50% -- lua/lazyvim/util/lazygit.lua"
Oct  7 11:55:52 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim diff --no-ext-diff --submodule --unified=3 --color=never --find-renames=50% -- lua/lazyvim/util/lazygit.lua"
Oct  7 11:55:52 |INFO| git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim diff --no-ext-diff --submodule --unified=3 --color=never --find-renames=50% -- lua/lazyvim/util/lazygit.lua (51.8553ms)
Oct  7 11:55:52 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim diff --no-ext-diff --submodule --unified=3 --color=never --find-renames=50% --cached -- lua/lazyvim/util/lazygit.lua"
Oct  7 11:55:52 |INFO| git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim diff --no-ext-diff --submodule --unified=3 --color=never --find-renames=50% --cached -- lua/lazyvim/util/lazygit.lua (50.7733ms)
Oct  7 11:55:55 |INFO| RunCommand command="Creating file 'C:\\Users\\GA50D~1.CER\\AppData\\Local\\Temp\\lazygit-3047991191\\LazyVim\\Oct  7 11.55.55.315179600.patch'"
Oct  7 11:55:55 |DEBU| RunCommand command="git apply --cached \"C:\\Users\\GA50D~1.CER\\AppData\\Local\\Temp\\lazygit-3047991191\\LazyVim\\Oct  7 11.55.55.315179600.patch\""
Oct  7 11:55:55 |INFO| git apply --cached "C:\Users\GA50D~1.CER\AppData\Local\Temp\lazygit-3047991191\LazyVim\Oct  7 11.55.55.315179600.patch" (54.4603ms)
Oct  7 11:55:55 |INFO| refreshing the following scopes in sync mode: files,staging
Oct  7 11:55:55 |INFO| refreshed merge conflicts in 0s
Oct  7 11:55:55 |DEBU| using cache for key status.showUntrackedFiles
Oct  7 11:55:55 |DEBU| RunCommand command="git status --untracked-files=all --porcelain -z --find-renames=50%"
Oct  7 11:55:55 |INFO| git status --untracked-files=all --porcelain -z --find-renames=50% (48.888ms)
Oct  7 11:55:55 |INFO| refreshed files in 56.8782ms
Oct  7 11:55:55 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim diff --no-ext-diff --submodule --unified=3 --color=never --find-renames=50% -- lua/lazyvim/util/lazygit.lua"
Oct  7 11:55:56 |INFO| git merge-base HEAD HEAD@{u} (55.4377ms)
Oct  7 11:55:56 |INFO| git merge-base HEAD refs/remotes/origin/main (54.4847ms)
Oct  7 11:55:56 |INFO| git -c log.showSignature=false log -g --abbrev=40 --format=%h%x00%ct%x00%gs%x00%p (129.096ms)
Oct  7 11:55:56 |INFO| postRefreshUpdate for reflogCommits took 1.0576ms
Oct  7 11:55:56 |INFO| git log HEAD --topo-order --oneline --pretty=format:%H%x00%at%x00%aN%x00%ae%x00%D%x00%p%x00%m%x00%s --abbrev=40 -300 --no-show-signature -- (65.5581ms)
Oct  7 11:55:56 |DEBU| using cache for key rebase.updateRefs
Oct  7 11:55:56 |INFO| postRefreshUpdate for commits took 0s
Oct  7 11:55:56 |DEBU| RunCommand command="git for-each-ref --sort=-committerdate --format=%(HEAD)%00%(refname:short)%00%(upstream:short)%00%(upstream:track)%00%(push:track)%00%(subject)%00%(objectname)%00%(committerdate:unix) refs/heads"
Oct  7 11:55:56 |INFO| git for-each-ref --sort=-committerdate --format=%(HEAD)%00%(refname:short)%00%(upstream:short)%00%(upstream:track)%00%(push:track)%00%(subject)%00%(objectname)%00%(committerdate:unix) refs/heads (59.7039ms)
Oct  7 11:55:56 |DEBU| RunCommand command="git symbolic-ref --short HEAD"
Oct  7 11:55:56 |ERRO| fatal: ref HEAD is not a symbolic ref
 command="git symbolic-ref --short HEAD"
Oct  7 11:55:56 |INFO| git symbolic-ref --short HEAD (48.9571ms)
Oct  7 11:55:56 |DEBU| RunCommand command="git branch --points-at=HEAD --format=%(HEAD)%00%(objectname)%00%(refname)"
Oct  7 11:55:56 |INFO| git branch --points-at=HEAD --format=%(HEAD)%00%(objectname)%00%(refname) (55.7454ms)
Oct  7 11:55:56 |INFO| postRefreshUpdate for localBranches took 0s
Oct  7 11:55:56 |DEBU| using cache for key rebase.updateRefs
Oct  7 11:55:57 |ERRO| Unexpected error when running cmd task: exit status 1; Failed command: C:\Users\<USERNAME>\scoop\shims\git.exe [git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium refs/heads/main --]
Oct  7 11:56:01 |DEBU| RunCommand command="git --version"
Oct  7 11:56:01 |INFO| git --version (52.6402ms)
Oct  7 11:56:01 |DEBU| RunCommand command="git -C C:\\Users\\<USERNAME> rev-parse --path-format=absolute --show-toplevel --absolute-git-dir --git-common-dir --is-bare-repository --show-superproject-working-tree"
Oct  7 11:56:01 |ERRO| fatal: not a git repository (or any of the parent directories): .git
 command="git -C C:\\Users\\<USERNAME> rev-parse --path-format=absolute --show-toplevel --absolute-git-dir --git-common-dir --is-bare-repository --show-superproject-working-tree"
Oct  7 11:56:01 |INFO| git -C C:\Users\<USERNAME> rev-parse --path-format=absolute --show-toplevel --absolute-git-dir --git-common-dir --is-bare-repository --show-superproject-working-tree (47.2322ms)
Oct  7 11:56:01 |INFO| Error getting repo paths: 'git -C C:\Users\<USERNAME> rev-parse --path-format=absolute --show-toplevel --absolute-git-dir --git-common-dir --is-bare-repository --show-superproject-working-tree' failed: fatal: not a git repository (or any of the parent directories): .git

Oct  7 11:56:03 |INFO| postRefreshUpdate for tags took 3.3671ms
Oct  7 11:56:03 |INFO| git -c log.showSignature=false log -g --abbrev=40 --format=%h%x00%ct%x00%gs%x00%p (99.3156ms)
Oct  7 11:56:03 |INFO| postRefreshUpdate for reflogCommits took 532.4µs
Oct  7 11:56:03 |DEBU| RunCommand command="git for-each-ref --sort=-committerdate --format=%(HEAD)%00%(refname:short)%00%(upstream:short)%00%(upstream:track)%00%(push:track)%00%(subject)%00%(objectname)%00%(committerdate:unix) refs/heads"
Oct  7 11:56:03 |INFO| git merge-base HEAD refs/remotes/origin/main (66.6082ms)
Oct  7 11:56:03 |ERRO| fatal: HEAD does not point to a branch
 command="git merge-base HEAD HEAD@{u}"
Oct  7 11:56:03 |INFO| git merge-base HEAD HEAD@{u} (67.1335ms)
Oct  7 11:56:03 |INFO| git log HEAD --topo-order --oneline --pretty=format:%H%x00%at%x00%aN%x00%ae%x00%D%x00%p%x00%m%x00%s --abbrev=40 -300 --no-show-signature -- (75.1873ms)
Oct  7 11:56:03 |DEBU| using cache for key rebase.updateRefs
Oct  7 11:56:03 |INFO| postRefreshUpdate for commits took 0s
Oct  7 11:56:03 |INFO| git for-each-ref --sort=-committerdate --format=%(HEAD)%00%(refname:short)%00%(upstream:short)%00%(upstream:track)%00%(push:track)%00%(subject)%00%(objectname)%00%(committerdate:unix) refs/heads (60.6756ms)
Oct  7 11:56:03 |DEBU| RunCommand command="git symbolic-ref --short HEAD"
Oct  7 11:56:03 |ERRO| fatal: ref HEAD is not a symbolic ref
 command="git symbolic-ref --short HEAD"
Oct  7 11:56:03 |INFO| git symbolic-ref --short HEAD (43.7641ms)
Oct  7 11:56:03 |DEBU| RunCommand command="git branch --points-at=HEAD --format=%(HEAD)%00%(objectname)%00%(refname)"
Oct  7 11:56:03 |INFO| git branch --points-at=HEAD --format=%(HEAD)%00%(objectname)%00%(refname) (46.8491ms)
Oct  7 11:56:03 |INFO| postRefreshUpdate for localBranches took 0s
Oct  7 11:56:03 |DEBU| using cache for key rebase.updateRefs
Oct  7 11:56:05 |INFO| git merge-base HEAD refs/heads/master (46.4889ms)
Oct  7 11:56:05 |DEBU| Error getting git config value for key: rebase.updateRefs. Error: the key is not found for [git config --get --null rebase.updateRefs]
Oct  7 11:56:05 |INFO| postRefreshUpdate for commits took 47.2939ms
Oct  7 11:56:05 |DEBU| using cache for key rebase.updateRefs
Oct  7 11:56:05 |DEBU| RunCommand command="git for-each-ref --sort=-committerdate --format=%(HEAD)%00%(refname:short)%00%(upstream:short)%00%(upstream:track)%00%(push:track)%00%(subject)%00%(objectname)%00%(committerdate:unix) refs/heads"
Oct  7 11:56:05 |INFO| git for-each-ref --sort=-committerdate --format=%(HEAD)%00%(refname:short)%00%(upstream:short)%00%(upstream:track)%00%(push:track)%00%(subject)%00%(objectname)%00%(committerdate:unix) refs/heads (47.2308ms)
Oct  7 11:56:05 |INFO| postRefreshUpdate for localBranches took 0s
Oct  7 11:56:05 |DEBU| using cache for key rebase.updateRefs
Oct  7 11:56:05 |DEBU| RunCommand command="git -C C:/Work/MEGA/Scripts diff --no-ext-diff --submodule --unified=3 --color=always --find-renames=50% --no-index -- /dev/null .nvim/svlangserver/index.json"
Oct  7 11:56:05 |ERRO| Unexpected error when running cmd task: exit status 1; Failed command: C:\Users\<USERNAME>\scoop\shims\git.exe [git -C C:/Work/MEGA/Scripts diff --no-ext-diff --submodule --unified=3 --color=always --find-renames=50% --no-index -- /dev/null .nvim/svlangserver/index.json]
Oct  7 11:56:06 |DEBU| RunCommand command="git -C C:/Work/MEGA/Scripts diff --no-ext-diff --submodule --unified=3 --color=always --find-renames=50% -- .nvim/svlangserver"
Oct  7 11:56:06 |INFO| postRefreshUpdate for menu took 2.1182ms
Oct  7 11:56:10 |DEBU| RunCommand command="git rev-parse --git-dir"
Oct  7 11:56:10 |INFO| git rev-parse --git-dir (51.7663ms)
Oct  7 11:56:10 |DEBU| RunCommand command="git -C C:\\Users\\<USERNAME>\\AppData\\Local\\nvim-data\\lazy\\LazyVim rev-parse --path-format=absolute --show-toplevel --absolute-git-dir --git-common-dir --is-bare-repository --show-superproject-working-tree"
Oct  7 11:56:10 |INFO| git -C C:\Users\<USERNAME>\AppData\Local\nvim-data\lazy\LazyVim rev-parse --path-format=absolute --show-toplevel --absolute-git-dir --git-common-dir --is-bare-repository --show-superproject-working-tree (56.5542ms)
Oct  7 11:56:10 |INFO| refreshing all scopes in async mode
Oct  7 11:56:10 |INFO| Refresh took 0s
Oct  7 11:56:10 |DEBU| RunCommand command="cmd /c title LazyVim - Lazygit"
Oct  7 11:56:10 |INFO| git symbolic-ref --short HEAD (44.5814ms)
Oct  7 11:56:10 |DEBU| RunCommand command="git branch --points-at=HEAD --format=%(HEAD)%00%(objectname)%00%(refname)"
Oct  7 11:56:10 |INFO| git branch --points-at=HEAD --format=%(HEAD)%00%(objectname)%00%(refname) (50.8656ms)
Oct  7 11:56:10 |DEBU| RunCommand command="git worktree list --porcelain"
Oct  7 11:56:10 |INFO| git worktree list --porcelain (59.0645ms)
Oct  7 11:56:10 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim rev-parse --path-format=absolute --absolute-git-dir"
Oct  7 11:56:11 |INFO| git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim rev-parse --path-format=absolute --absolute-git-dir (58.8671ms)
Oct  7 11:56:11 |INFO| postRefreshUpdate for worktrees took 0s
Oct  7 11:56:11 |INFO| postRefreshUpdate for localBranches took 0s
Oct  7 11:56:11 |INFO| refreshing the following scopes in async mode: files
Oct  7 11:56:11 |DEBU| using cache for key status.showUntrackedFiles
Oct  7 11:56:11 |INFO| Refresh took 0s
Oct  7 11:56:11 |DEBU| RunCommand command="git status --untracked-files=all --porcelain -z --find-renames=50%"
Oct  7 11:56:11 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim diff --no-ext-diff --submodule --unified=3 --color=always --find-renames=50% -- lua/lazyvim/util"
Oct  7 11:56:11 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim diff --no-ext-diff --submodule --unified=3 --color=always --find-renames=50% -- lua/lazyvim/util"
Oct  7 11:56:11 |INFO| git status --untracked-files=all --porcelain -z --find-renames=50% (54.7535ms)
Oct  7 11:56:11 |INFO| postRefreshUpdate for submodules took 0s
Oct  7 11:56:11 |INFO| postRefreshUpdate for files took 8.3694ms
Oct  7 11:56:11 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim diff --no-ext-diff --submodule --unified=3 --color=always --find-renames=50% -- lua/lazyvim/util"
Oct  7 11:56:12 |INFO| Heap memory in use: 7.3 MB
Oct  7 11:56:12 |INFO| refreshed merge conflicts in 0s
Oct  7 11:56:12 |DEBU| using cache for key status.showUntrackedFiles
Oct  7 11:56:12 |DEBU| RunCommand command="git status --untracked-files=all --porcelain -z --find-renames=50%"
Oct  7 11:56:12 |INFO| git status --untracked-files=all --porcelain -z --find-renames=50% (49.6638ms)
Oct  7 11:56:12 |INFO| refreshed files in 57.9452ms
Oct  7 11:56:12 |INFO| Refresh took 57.9452ms
Oct  7 11:56:12 |INFO| postRefreshUpdate for submodules took 0s
Oct  7 11:56:12 |INFO| postRefreshUpdate for files took 7.3093ms
Oct  7 11:56:12 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim diff --no-ext-diff --submodule --unified=3 --color=always --find-renames=50% -- lua/lazyvim/util"
Oct  7 11:56:22 |INFO| refreshing the following scopes in sync mode: files
Oct  7 11:56:22 |INFO| refreshed merge conflicts in 0s
Oct  7 11:56:22 |DEBU| using cache for key status.showUntrackedFiles
Oct  7 11:56:22 |DEBU| RunCommand command="git status --untracked-files=all --porcelain -z --find-renames=50%"
Oct  7 11:56:22 |INFO| git status --untracked-files=all --porcelain -z --find-renames=50% (50.7568ms)
Oct  7 11:56:22 |INFO| refreshed files in 60.8899ms
Oct  7 11:56:22 |INFO| Refresh took 60.8899ms
Oct  7 11:56:22 |INFO| postRefreshUpdate for submodules took 104.5µs
Oct  7 11:56:22 |INFO| postRefreshUpdate for files took 7.4975ms
Oct  7 11:56:22 |DEBU| RunCommand command="git -C C:/Users/<USERNAME>/AppData/Local/nvim-data/lazy/LazyVim diff --no-ext-diff --submodule --unified=3 --color=always --find-renames=50% -- lua/l
```

My OS Is Windows 11 Pro.

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.

**Comment by stefanhaller** [comment] 2024-10-07 10:25
Thanks for the detailed report, but I'll close this as a duplicate of #1453.

Custom pagers don't work on Windows, this is well documented (e.g. [here](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md)).

**Closed by stefanhaller** 2024-10-07 10:25 UTC
Labels: bug
