### ISSUE TITLE
lazygit:4: maximum nested function level reached

### ISSUE THREAD

**Issue by PKUFlyingPig** [jesseduffield/lazygit#735] opened 2020-03-24 15:42 UTC
**Describe the bug**
When I want to start lazygit in oh-my-zsh, the error below occurred:
lazygit:4: maximum nested function level reached

**Screenshots**
<img width="741" alt="image" src="https://user-images.githubusercontent.com/60659728/77446223-15ff7880-6e29-11ea-95b4-23b0554c9297.png">

**Desktop (please complete the following information):**
 - OS
 - Lazygit Version [e.g. v0.1.45]

**Comment by glvr182** [comment] 2020-03-28 20:11
What version of lazygit are you on?

**Comment by jesseduffield** [comment] 2020-08-23 23:30
closing due to staleness and inability to reproduce. @PKUFlyingPig if you're able to tell us your version and ideally a repro where this occurs, we can reopen

**Closed by jesseduffield** 2020-08-23 23:30 UTC
Labels: bug
