### ISSUE TITLE
Panic when paste string containing newlines into new branch name

### ISSUE THREAD

**Issue by JonathanAquino** [jesseduffield/lazygit#1202] opened 2021-03-27 00:06 UTC
**Describe the bug**
Sometimes when I copy and paste a Jira issue number into the dialog shown below, the program crashes and I see a panic error message.

![image](https://user-images.githubusercontent.com/90288/112703331-c98fb400-8e53-11eb-8e98-4cb31a3616ea.png)

    panic: runtime error: index out of range [11] with length 11

    goroutine 1 [running]:
    github.com/jesseduffield/gocui.(*View).writeRune(0xc00032d080, 0xb, 0x0, 0x0, 0xc000189620, 0x1047d0c)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/edit.go:359 +0x6d8
    github.com/jesseduffield/gocui.(*View).EditWrite(0xc00032d080, 0x0)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/edit.go:68 +0x6b
    github.com/jesseduffield/lazygit/pkg/gui.(*Gui).defaultEditor(0xc00014e000, 0xc00032d080, 0x20000d, 0x100)
        /home/runner/work/lazygit/lazygit/pkg/gui/editors.go:72 +0x185
    github.com/jesseduffield/gocui.EditorFunc.Edit(0xc0004a1480, 0xc00032d080, 0x8000d, 0x16df000)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/edit.go:27 +0x4b
    github.com/jesseduffield/gocui.(*Gui).onKey(0xc00013e7e0, 0xc00008d620, 0x16df060, 0x1)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:871 +0x344
    github.com/jesseduffield/gocui.(*Gui).handleEvent(0xc00013e7e0, 0xc00008d620, 0x0, 0x0)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:551 +0x46
    github.com/jesseduffield/gocui.(*Gui).consumeevents(0xc00013e7e0, 0xc000135320, 0x0)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:525 +0x1c9
    github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc00013e7e0, 0xc000000004, 0xc00025fa90)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:511 +0x290
    github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc00014e000, 0x0, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:504 +0x505
    github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc00014e000, 0x0, 0x1707f89)
        /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:517 +0x108
    github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc00020fc00, 0xc0001ee6c0, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/app/app.go:240 +0x6b
    main.main()
        /home/runner/work/lazygit/lazygit/main.go:126 +0xb3b

**To Reproduce**
1. Press 3 to to the Branches panel
2. Press n to create a new branch
3. Paste in the following text (including the newlines):
```
RWREPT-3369



```
The branch is created but the above panic happens.

**Expected behavior**
The branch is created and no panic happens. Newlines should be removed automatically.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Lazygit Version 0.24

**Additional context**

**Comment by jesseduffield** [comment] 2021-10-17 06:42
I can't reproduce this locally on master, but I happen to have also just refactored how edit functionality works (i.e. typing into a prompt) and I expect that to be more stable. I'm gonna close this issue but let me know if you still get the problem on the latest master

**Closed by jesseduffield** 2021-10-17 06:42 UTC
Labels: bug
