### ISSUE TITLE
 Hold down arrow key to switch file,  diff window stop render.

### ISSUE THREAD

**Issue by LucaXiang** [jesseduffield/lazygit#1265] opened 2021-04-12 22:13 UTC
**Describe the bug**
1. Unstaged Changes stop update
2. Exit with error message "cannot kill child process"

**To Reproduce**
1.  Enter Files Window
2.  **Hold Down** the arrow keys (up or down) to switch files, (Single click do not happen)
3.  Un staged changes  or diff window stop update

**Expected behavior**
Un staged Changes windows should to update.

**Screenshots:**
![Snipaste_2021-04-13_00-00-07.png](https://i.loli.net/2021/04/13/xC2Ote1rkplGfWD.png)
![Snipaste_2021-04-13_00-00-30.png](https://i.loli.net/2021/04/13/i9xySEAhpCu8cnU.png)

**Desktop:**
 - OS: Windows
 - Lazy Git Version : v0.27.4

**Additional context**
 I tried it in WSL2 (Ubuntu) and it doesn't have this problem

v0.35 still happen

**Comment by LucaXiang** [comment] 2021-04-12 22:25
I tried it in v25 v26 v27 have same problem

**Comment by MikeVensel** [comment] 2022-01-10 15:18
I am still having this issue very frequently on v0.31.4

**Comment by LucaXiang** [comment] 2022-01-16 15:52
> I am still having this issue very frequently on v0.31.4

guy, iguy i recommend you use wsl2 (windows subsystem linux).
![1642348319(1)](https://user-images.githubusercontent.com/22201628/149667229-f7e57185-7312-4f7d-aea7-e16b490e8fee.jpg)

**Comment by LucaXiang** [comment] 2022-01-16 15:52
> I am still having this issue very frequently on v0.31.4

**Comment by LucaXiang** [comment] 2022-01-16 15:52
> I am still having this issue very frequently on v0.31.4

![1642348319(1)](https://user-images.githubusercontent.com/22201628/149667274-088e3e7d-2049-43e7-a218-b06b214c5304.jpg)
guy i recommend you use wsl2 (windows subsystem linux).

**Comment by MikeVensel** [comment] 2022-01-16 17:13
I can understand suggesting WSL 2 as a work around temporarily, but I don't think it is unreasonable to ask for a fix for this issue. Lazygit claims to support Windows and this bug makes using the tool on Windows irritating.

**Comment by Aziks0** [comment] 2022-05-12 20:31
This is a **major** issue for Windows users, unfortunately. I got to a point where I couldn't use lazygit for more than a few seconds after running it _(unless I wasn't using the file tree, obviously)_. I even stopped using it for the last 2 months.

---

I've done some digging by checking the log tho, here's what I've found:

#### 1. After executing `lazygit` at the source of my repo, the selected file is the **folder** `.tasks`. The `main view` appears and reports `error: Could not access '.tasks/null'`, which is expected.

![lg_launch-folder](https://user-images.githubusercontent.com/36425380/168148766-f1a08672-9d5d-4f7f-b602-b86a70246078.png)

- A first `RunCommand command="git diff --submodule --no-ext-diff --unified=3 --color=always --no-index -- /dev/null .tasks"` is executed, it seems to work without error.
- A second `RunCommand command="git diff [...] .tasks"` is executed, and is followed by the error `error when running cmd task: invalid argument` and then _(I guess)_ the "goroutine" exits itself.

#### 2. I select the next file in the tree, `.tasks/bump.v`. The `main view` appears instantly, it contains the file diff, nothing weird here.

![lg_file](https://user-images.githubusercontent.com/36425380/168152033-27533706-abd7-4e6e-9650-58cb7bbdfbc8.png)

- A first `RunCommand command="git diff --submodule --no-ext-diff --unified=3 --color=always --no-index -- /dev/null .tasks/bump.v"` is executed, followed by the error `error when running cmd task: invalid argument`. It is **not followed**  by `error status 1`.
- A few seconds after the first one, a second `RunCommand command="git diff [...] .tasks/bump.v"` is executed, followed by the error `error when running cmd task: invalid argument`. It is followed by the error `error when running cmd task: TerminateProcess: Access denied`, and then `error status 1`.

#### 3. I hold down <kbd>↓</kbd> _(down arrow key)_ to walk down the file tree. The `main view` freezes.

![lg_walk-file-tree](https://user-images.githubusercontent.com/36425380/168156956-03e357e9-1627-4ab9-a12f-247396105c5c.png)

- Tons of `RunCommand command="git diff [...] {FILE_NAME}"`, but **not a single** `invalid argument`, nor `TerminateProcess: Access denied`, nor `exit status 1`.

#### 4. I exit `lazygit`, and, surprise surprise: `cannot kill child process`.

---

Ok, so now, what happens if I do everything again, but instead of holding down <kbd>↓</kbd>, I press it multiple times ?

#### 1. Executing `lazygit` at the source of my repo.

![lg_launch-folder](https://user-images.githubusercontent.com/36425380/168159213-90af94cd-8291-4e5c-83c5-f09aa6759d75.png)

- **same as before**

#### 2. Pressing <kbd>↓</kbd> multiple times.

![lg_walk-file-tree](https://user-images.githubusercontent.com/36425380/168159890-c854ffcd-bc5c-446d-89dc-365b7be6fc3a.png)
_(I spare you the very-very-very-long screenshot, but the log file is available at the end of my comment)_

- `RunCommand command="git diff [...] {FILE_NAME}"`
- Error `invalid argument`
- Error `TerminateProcess: Access Denied`
- `exit status 1`
- Repeat

The `main view` doesn't freeze, it shows what is expected: **the files diff**.

#### 3. I exit `lazygit`, and, surprise surprise: **no issue**.

[Holding <↓> log file](https://github.com/jesseduffield/lazygit/files/8681847/lazygit_walk_file_tree_error.log)
[Pressing <↓> multiple times log file](https://github.com/jesseduffield/lazygit/files/8682299/lazygit_walk_file_tree.log)

**Comment by nikit-psl** [comment] 2022-06-01 22:29
A similar thing is happening for me when I'm using `lazygit` inside toggleterm in neovim.
Terminal - Alacritty
OS - Windows 11

It's working fine when I'm using lazygit directly in Alacritty though. Also, this only happens when I keep the down key pressed and doesn't happen when I keep the up key pressed.

**Comment by jesseduffield** [comment] 2022-06-18 03:42
great investigation @Aziks0. Some things I've noted while taking a look at the code just now:
1) The start of the process is typically to call gui.newPtyTask, which will itself only call gui.newCmdTask if there's no custom pager being used OR if we're on windows because that gui.newPtyTask function is called is overridden for windows in `pkg/gui/pty_windows.go` (this is because the pty library doesn't yet support windows (see https://github.com/creack/pty/pull/109). I wonder if the problem is that the git command _does_ use a pager (e.g. `less`) and so never returns an EOF to the scanner, meaning we get stuck on `scanner.Scan()`. Scanners block while waiting for new content, but we could swap out the scanner with a plain old reader and would then be able to deal with a lack of new content.

2) The in-built process killing method doesn't handle child processes of a windows process. I've got a PR to handle this, adapted from the approach we take in lazydocker. @Aziks0 would you be able to see if the issue persists on this PR? https://github.com/jesseduffield/lazygit/pull/2006

**Comment by Aziks0** [comment] 2022-06-18 08:43
1. I've tried with and without a pager a few months ago, it didn't change anything to not have one. I've retried today, no difference.
2. The issue persist, unfortunately :(. It is not better or worst, just the same as before.

**Comment by Aziks0** [comment] 2022-06-18 09:45
Btw, if I hold down <kbd>↓</kbd> instantly after executing lazygit, the issue appears instantly. If I wait a few seconds before holding down <kbd>↓</kbd>/<kbd>↑</kbd>, the issue appears more randomly.

https://user-images.githubusercontent.com/36425380/174432026-88c1d836-33be-42fe-978c-782f2ea7af49.mp4

**Comment by adriancostin6** [comment] 2023-03-06 16:14
I am also experiencing this annoying issue. Really liked using lazygit, but no I'm back to using the command line git tools, as it is better than pulling my hair out every time the diff view freezes. Any updates on this? Can I do something to help?

**Comment by mark2185** [comment] 2023-03-06 18:19
Could you maybe try the latest `master`? There were a few updates regarding `gocui`

**Comment by LucaXiang** [comment] 2023-03-06 18:51
After upgrading to the latest lazygit, the problem never occurred again

**Comment by AndrewSav** [comment] 2023-03-07 06:34
may be we can make a release soon then? it's a pretty major thing to push out IMO!

**Comment by mark2185** [comment] 2023-03-07 06:37
Last release was a month ago, does it still happen with `v0.37.0`?

**Comment by AndrewSav** [comment] 2023-03-07 06:46
Yes, still happening on v0.37.0
![2023-03-07_19-43-42](https://user-images.githubusercontent.com/658865/223344643-a246cb33-22ba-4d2d-b40b-024186287b1b.png)

Unstaged changes stop updating too.

**Comment by mark2185** [comment] 2023-03-07 07:50
@AndrewSav and just to confirm, you don't have any issues on latest master as well?

**Comment by mark2185** [comment] 2023-03-07 10:27
> @mark2185 I can try latest master if there is a release that is built from the latest master.

There isn't, I meant could you try building the latest `master` and see if it happens there as well?

**Comment by adriancostin6** [comment] 2023-03-08 10:18
@mark2185 done. results below. os: windows 10

![lazygit](https://user-images.githubusercontent.com/32834752/223686694-0628bd9f-1e8c-4a1b-b399-446913c3ae47.gif)

**Comment by adriancostin6** [comment] 2023-07-11 09:34
hello, just wanted to follow up to see if anyone is still looking at this?

**Comment by AndrewSav** [comment] 2023-07-13 23:48
Hey, just wanted to share my experience. I did a few things which did not completely eliminate the occurrence of the issue, but brought down the frequency with which it's occurring. I think this may be a combination of factors:

- It happen less with (new) Windows Terminal. If using alacrity or conemu I can reproduce it much faster
- It happens less if git is NOT installed from scoop, scoop adds a shim which adds friction, again when git is installed from scoop I can reproduce it faster
- When `lazygit` gets to a bugged state there are one or more suspended `git` processes sitting in the task manager. I believe this explains scanner not scanning - the pipe is there but the process is suspended. If I run `Get-Process git | Stop-Process` the panels start refreshing again. I do not offer this as a work around, since it's much simpler just to quit `lazygit` and re-run it, just as an additional data point.

Replacing scanner with a reader as suggested above might help, and also if someone smart enough can figure out why we get these suspended git processes, we might finally resolve this issue.

**Comment by AndrewSav** [comment] 2023-07-14 05:04
I attempted to do a minimal fix so that when the scanner is blocked it does not hang the task. It seems to work for me even with all the shims and conemu. Can someone please test? https://github.com/AndrewSav/lazygit/commit/44b18f12cbcaf8e99f919f1cdf4532cecd39c9df

**Comment by AndrewSav** [comment] 2023-07-15 22:24
So the above seems to work for me in terms of fixing the display issue, however we still have suspended git processes left behind. I think this is a timing issue, and what might be happening is this:

- (1) `lazygit` spawns git process, shim is on path
- (2) shim is started and is trying to create child process
- (3) `lazygit` detects that current item in the UI changed and tries to start a task of running `git` command to get the diff window
- (4) `lazygit` attempts to kill the old process (1) and the children
- (5) first, `lazygit` enumerates all the children of the shim, there are none so far
- (6) at this point shim creates child process [suspended](https://github.com/kiennq/scoop-better-shimexe/blob/36a6c5284149d1bb17d4d5536dc00a331189ad93/shim.cpp#L143) and connects the stdout pipe
- (7) now `lazygit` kill the shim, but does not kill the child because it was not there when it enumerated processes (5) for children
- (8) since the shim did not have a chance to un-suspend the child before getting killed, the suspended child persists

At this point we are left with a suspended process which both causes the scanner to block and remains there until someone deletes it manually or the system is rebooted, we just leaked this process. 

I feel that fixing this may be quite tricky especially if several shims are involved: the scoop one and the git for windows own one. The workaround here for a user, would be not to use shims and run the actual git process directly.

**Comment by adriancostin6** [comment] 2023-07-16 10:11
@AndrewSav, thanks for all the work you put in for this seemingly dead issue, that has been here for quite a while.

You just opened my eyes to why this happens with your clear explanations. Kudos to you!

I do use scoop, and never thought of the shims. Will try installing them directly, and see if I get better results.

**Comment by jesseduffield** [comment] 2023-07-16 11:52
Great investigation @AndrewSav . I've googled around a bit to see if there's some way to resolve this but haven't had any luck so far

**Comment by jesseduffield** [comment] 2023-07-16 11:54
Actually this might help: https://gist.github.com/hallazzang/76f3970bfc949831808bbebc8ca15209

**Comment by AndrewSav** [comment] 2023-07-16 20:36
@jesseduffield, thanks, any point submitting PR with the display issue fix (above)?

**Comment by AndrewSav** [comment] 2023-07-21 09:44
@jesseduffield I still would like to know if you would be interested in the PR. I used the patched version this week and in my workflow I have not encountered any issues

**Closed** 2023-07-21 23:12 UTC
Labels: bug

**Comment by AndrewSav** [comment] 2023-10-02 02:40
I'm using `get-process git | ?{($_.Threads.ThreadState -eq "Wait").Count -eq $_.Threads.Count }` to kill all those dozens of `git.exe` left behind in the meanwhile.

**Comment by jesseduffield** [comment] 2023-10-02 04:57
@AndrewSav that command won't be necessary with https://github.com/jesseduffield/lazygit/pull/2806 right? Like that command is to just retrospectively fix up the zombie processes right?

**Comment by AndrewSav** [comment] 2023-10-02 06:55
@jesseduffield we fixed lazygit UI misbehaving, but the way the processes are spawning still lead to orphaned git processes, it just no longer makes the UI stop updating.

**Comment by AndrewSav** [comment] 2023-10-02 07:02
@jesseduffield the [link](https://gist.github.com/hallazzang/76f3970bfc949831808bbebc8ca15209) you posted earlier should be the fix for the underlying issue, but I was not prepared to see that through, since while the direction it takes looks promising to me I also foresee problems with that implementation because of the timing issues. That's why I aimed at the minimal display issues fix.

**Comment by jesseduffield** [comment] 2023-10-11 11:53
@AndrewSav ah yes, silly me for forgetting. For the record there's work being done over at https://github.com/jesseduffield/kill/pull/1 to address the underlying issue
