### ISSUE TITLE
Alternative git-dir and work-tree

### ISSUE THREAD

**Issue by 80KiloMett** [jesseduffield/lazygit#881] opened 2020-06-29 15:16 UTC
**Is your feature request related to a problem? Please describe.**
I organize my dotfiles in a bare git repository (as described [here](https://www.atlassian.com/git/tutorials/dotfiles)). This means that the git directory for this particular repo is not named ".git" and the work tree is my entire home directory.

**Describe the solution you'd like**
I'd like to be able to give lazygit an alternative git-dir and work tree via a flag, like so
lazygit --git-dir /path/to/alternate/gitdir --work-tree /path/to/work-tree/root

I have already tried setting the GIT_DIR and GIT_WORK_TREE environment variables. With these set lazygit wouldn't give me an error anymore but got stuck at startup (I waited about 10min before sending a keyboard interupt). I thought this might have something to do with the size of the work-tree (my home dir). But it also happened when I created a bare test repo with a smaller working tree than my home directory.

**Comment by micmarty** [comment] 2020-08-20 14:23
I also miss that. Maybe there's a workaround? 
All in all, lazygit for managing would be a blessing.

**Comment by sebastiangelotte** [comment] 2020-09-04 10:01
I would love this. This is the only thing preventing me from using lazygit for everything git in my workflow.

**Comment by jesseduffield** [comment] 2020-09-27 05:44
closing as a duplicate of https://github.com/jesseduffield/lazygit/issues/778 but do not fret, The feature is almost done https://github.com/jesseduffield/lazygit/pull/1023

**Closed** 2020-09-27 05:45 UTC
Labels: enhancement
