### ISSUE TITLE
Error when deleting merge commit

### ISSUE THREAD

**Issue by OliverJAsh** [jesseduffield/lazygit#3698] opened 2024-06-28 11:00 UTC
**Describe the bug**
Error when deleting merge commit.

**To Reproduce**

1. Try to delete a merge commit

**Expected behavior**
The deletion works.

**Screenshots**

https://github.com/jesseduffield/lazygit/assets/921609/67013f2b-85bb-4d6b-b068-f4422f1b3bf5

**Version info:**
```
commit=, build date=, build source=nix, version=0.42.0, os=darwin, arch=arm64, git version=2.45.1
```

```
git version 2.45.1
```

**Additional context**

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.

**Comment by mark2185** [comment] 2024-06-28 11:13
Just to confirm, dropping non-merge commits works?

**Comment by stefanhaller** [comment] 2024-06-28 12:09
This is a duplicate of #3164, and there's some explanation there. (The paragraph with the suggested workaround is out of date, we no longer allow that.)

I could have sworn we added code to disallow dropping merges outside of a rebase, but I must have dreamed that.

**Closed** 2024-06-28 13:24 UTC
Labels: bug
