### ISSUE TITLE
merge, many conflict, so i launch lazygit to resolve it, then i get this.

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [jesseduffield/lazygit#1352] opened 2021-06-03 12:49 UTC
![image](https://user-images.githubusercontent.com/2133400/120647421-2be8de80-c4ad-11eb-95d4-1f3fbb2968c6.png)

**Comment by nikbrunner** [comment] 2021-06-04 12:24
I just the same error, and came here looking for a solution. 
I wanted to rebase and got a lot of conflicts I need to resolve.

**Comment by jesseduffield** [comment] 2021-06-05 03:25
@nikbrunner @FinallyFinancialFreedom could you see if the issue is resolved by this PR: https://github.com/jesseduffield/lazygit/pull/1348/files

**Comment by FinallyFinancialFreedom** [comment] 2021-06-05 03:58
i will wait until a new version in homebrew. i find this pr is merged 2 minutes ago.

**Comment by jesseduffield** [comment] 2021-06-05 04:16
Should be fixed in v0.28.2

**Comment by FinallyFinancialFreedom** [comment] 2021-06-05 06:12
> Should be fixed in v0.28.2
yes, i just confirmed this.

**Comment by FinallyFinancialFreedom** [comment] 2021-06-05 06:12
> Should be fixed in v0.28.2

yes, i just confirmed this

**Closed** 2021-06-05 06:11 UTC
Labels: bug

**Comment by nikbrunner** [comment] 2021-06-05 07:09
@jesseduffield Works thank you :)
