### ISSUE TITLE
Tabs are stripped in the diff view

### ISSUE THREAD

**Issue by xxdavid** [jesseduffield/lazygit#302] opened 2018-10-06 21:05 UTC
Before everything else, thank you for this excellent app! Love it. ❤️

**Describe the bug**
In the diff view, tabs at the beginning of line are stripped and all the lines are shifted to the left.

**To Reproduce**
Make a file with tabs used for indenting inside your repo, open the repo in lazygit.

**Expected behavior**
I would expect tabs not being stripped (spaces aren't stripped). Are they removed on purpose or is it a bug?

**Screenshots**
<img width="1025" alt="screenshot 2018-10-06 at 22 48 51" src="https://user-images.githubusercontent.com/3393339/46575738-5b24b600-c9bb-11e8-8875-c24e39ef11fd.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave, tested on Fedora too
 - Lazygit Version: v0.31

**Comment by xxdavid** [comment] 2018-10-08 04:32
I think I can supply a PR if it's a bug.

**Comment by jesseduffield** [comment] 2018-10-10 07:21
hmm I'm amazed I've never noticed that before myself. Probably because at work we use spaces not tabs so it's not noticeable in that context. If you want to submit a PR that would be much appreciated :)

**Comment by xxdavid** [comment] 2018-10-15 11:07
Sorry for a late response.

I'm working on this. But it turned out it'll probably be much harder to implement than I originally thought.
Tabs are, as defined in ASCII, not printable characters. So my idea was to replace them with a fixed number  of spaces. My initial code did just that. When I was writing the tests I realized this doesn't handle the cases when there are some chars *before* a tab. So I rewrote it to reflect that too.
But then I became aware of two things more difficult to handle.
Some chars don't have width equal to 1 (either they aren't printable or they are longer). There is a POSIX solution for this – [`wcwidth` ](http://man7.org/linux/man-pages/man3/wcwidth.3.html), the're also a [Go implementation](https://github.com/jquast/wcwidth) but I don't have any idea how will this behave on Windows.
The second problem are [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code) used primarily for coloring the output. They usually start with `ESC`, `[`, then there are some numbers and semicolons and they end with `m`. The issue with this is that the characters in between are regular characters with width 1 and they mess up the space counter because they are interpreted by terminals and thus not visible. One solution to this may be skip everything between `ESC [` and `m` but I don't know if it'll work universally.

Maybe I'm just doing it totally wrong... The easiest way would be to force the `fmt.Fprint` function to print the tabs as they are and let terminal to handle them but I don't know how... Do you have any suggestions?

**Comment by xxdavid** [comment] 2018-12-03 13:40
Any idea on this, anyone?

**Comment by xxdavid** [comment] 2018-12-03 14:05
I have a suspicion that there's a problem with `gocui` because even printing `a\tb` to a `View` shows as `ab`...

**Comment by glvr182** [comment] 2018-12-03 14:55
I don't think the issue is with gocui, but with the underlying termbox. This i base on the fact that we have issues open with foreign characters. They things might be related

**Comment by xxdavid** [comment] 2018-12-03 22:11
(Sorry, I just don't know why I clicked on the close button…)

**Comment by jesseduffield** [comment] 2018-12-05 08:39
sorry for not getting around to this in a while. Those indeed sound like tricky issues to solve. I would be satisfied with a first-cut solution that dealt with the terminal escape codes but didn't deal with variable-width characters, because they are just generally hard to deal with anyway and I think for the bulk of users seeing tabs is more important than seeing variable width characters

**Comment by xxdavid** [comment] 2018-12-07 14:15
@jesseduffield 
I agree it's better then nothing, for sure. We can do it for now.
But at work we often indent key and value like this:
```perl
{
    first   => 1,
    second  => 2,
    threeee => 3,
}
```
(There's always 1 tab between the key and `=>`.) And that wouldn't work. It's not that important but I'd be happy if we could handle even this cases.

I'm OK with not handling the wide chars, the vast majority of code uses only ASCII.

@glvr182 
My implementation does just that (with different key and default set to 4).

Should I submit a PR with the initial implementation doing just the naive tab to `n` spaces replacement?

**Comment by jesseduffield** [comment] 2018-12-09 10:56
ah I just came back here to say that I've put up a step-1 PR: https://github.com/jesseduffield/lazygit/pull/348/files

Was your implementation much different? If not I'll just merge the PR as-is :)

**Comment by xxdavid** [comment] 2018-12-09 23:13
Looks good to me.
My implementation operated on strings so it was probably less performant. On the other hand, this implementation may be harder to make more robust as it is run *inside* a loop (you can't easily share variables between iterations).
I think you can merge it. :)

**Comment by jesseduffield** [comment] 2019-11-11 12:37
closing as I believed this is resolved, but if it's not let me know :)

**Closed by jesseduffield** 2019-11-11 12:37 UTC
