### ISSUE TITLE
Merge error by arg `-e`

### ISSUE THREAD

**Issue by jerviscui** [jesseduffield/lazygit#2190] opened 2022-09-29 11:34 UTC
**Describe the bug**

When I was using args `-e` for git merge, the program died.

**To Reproduce**

1. Setting `config.yml`:

	```
	git:
	  merging:
	    # extra args passed to `git merge`, e.g. --no-ff
	    args: '-e'
	```

2. Then merge by lazygit,
3. lazygit will hang by this
![image](https://user-images.githubusercontent.com/6396748/193020933-9a7c3c9b-591e-4e46-81ad-088c20f971fa.png)

**Expected behavior**

I'm just trying. I don't have a good plan.

**Version info:**

commit=367b0d331836c90c015bf0c45f88612f3d94d08a, build date=2022-07-20T09:27:56Z, build source=binaryRelease, version=0.35, os=windows, arch=amd64
git version 2.35.1.windows.2

**Comment by mark2185** [comment] 2022-09-29 11:36
Could you please fill out the entire template?

**Comment by jerviscui** [comment] 2022-09-30 06:54
I have updated the report.

**Comment by mark2185** [comment] 2022-09-30 06:58
Ah, that hangs because it tries invoking `$EDITOR`.

Could you try setting the flags to `--no-commit` and then commit from within `lazygit`? If you wish to open the editor to do that, go to the `Files` panel `(2)` and press `C` (uppercase). That should do the same as you are trying to do now.

**Comment by Ryooooooga** [comment] 2022-09-30 10:43
One solution is to override a merge action with a custom command.

```yaml
customCommands:
  - key: M
    command: git merge -e {{.SelectedLocalBranch.FullRefName}}
    context: localBranches
    subprocess: true
    prompts:
      - type: confirm
        title: Merge
        body: Are you sure you want to merge '{{.SelectedLocalBranch.Name}}' into '{{.CheckedOutBranch.Name}}'?
```

**Comment by jerviscui** [comment] 2022-10-17 09:51
@mark2185 @Ryooooooga Thanks very much.

Yes, I check the files during the merge process and perhaps make a little change to prevent some local files overwrite by the branch directly.
Most of the time I expect merge to commit automatically, so I think I need a custom command with args `--no-commit --no-ff`.

Thanks again.

**Comment by jerviscui** [comment] 2022-10-17 09:54
How can I remove the tag `bug`?

**Comment by mark2185** [comment] 2022-10-17 09:55
If the issue is solved, you can close it.

If it's a `feature request`, I'll mark it so.

Just tell me which is it :sweat_smile:

**Closed** 2022-10-17 09:57 UTC
Labels: bug
