### ISSUE TITLE
NeoVim unexpected behavior 

### ISSUE THREAD

**Issue by ilovehans10** [jesseduffield/lazygit#653] opened 2020-02-20 19:12 UTC
**Describe the bug**
When lazygit is used to edit a file it will cause NeoVim to open in search mode with /00/00 in the search bar and on the first time opening a file if the file has contents it will replace the first character with a "g"

**To Reproduce**
1. Open lazygit
2. Hit e to edit file under the cursor
3. NeoVim will open having changed the first character and in search mode

**Expected behavior**
I expect for NeoVim to open as it normally does allow me to edit the file and allow me to save and exit.

**Screenshots**

https://asciinema.org/a/HYdeBetGT6yEkHQXRmRRMCki4

**Desktop (please complete the following information):**
 - OS: macOS Mojave (darwin)
 - Lazygit Version 0.14.3
 - The last commit id if you built project from sources (run : ```git-rev parse HEAD```)

**Additional context**
I don't think that my vimrc has any effect on this status but it can be found here if there is any chance of that [https://github.com/ilovehans10/dotfiles](https://github.com/ilovehans10/dotfiles)

**Comment by ilovehans10** [comment] 2020-02-21 19:06
Upon further testing I have come to realize that editing the file is not even necessary and that simply opening Lazygit closing Lazygit and opening NeoVim will lead to /00/00^G appearing in the search bar and the first character to be converted to a g as described in my initial report. I will be seeing if I can recreate this error on my home device when I have access to it, but until then any suggestions are appreciated.

**Comment by FinallyFinancialFreedom** [comment] 2020-04-03 13:58
i encountered the same problem.

**Comment by FinallyFinancialFreedom** [comment] 2020-04-05 14:25
> Upon further testing I have come to realize that editing the file is not even necessary and that simply opening Lazygit closing Lazygit and opening NeoVim will lead to /00/00^G appearing in the search bar and the first character to be converted to a g as described in my initial report. I will be seeing if I can recreate this error on my home device when I have access to it, but until then any suggestions are appreciated.
> Edit: I have also added the [fix](https://github.com/jesseduffield/lazygit/issues/451#issuecomment-494416112) suguested in #451, but it hasn't seemed to have any effect.

@ilovehans10 try to uninstall coc nvim , this problem will gone. But coc is a must have plugin.

**Comment by steelsojka** [comment] 2020-07-15 11:58
I get this same problem in nvim without using coc.nvim, So I don't think this is related to coc.nvim.

**Comment by jesseduffield** [comment] 2020-08-24 10:17
I am not really sure how to troubleshoot this one, I'm not well versed in neovim I'm afraid

**Comment by Liberatys** [comment] 2021-01-15 12:09
I can't reproduce the issue outlined ^^ maybe update nvim and lazygit ?

**Comment by jesseduffield** [comment] 2021-04-06 22:58
@ilovehans10 @steelsojka can you guys test this out on the latest release?

**Comment by FinallyFinancialFreedom** [comment] 2021-04-11 04:06
> @ilovehans10 @steelsojka can you guys test this out on the latest release?

i have tried the lastest version,0.25.1, the problem is fixed.

**Comment by jesseduffield** [comment] 2021-04-11 05:19
Alrighty, closing, but let me know if any more issues arise :)

**Closed by jesseduffield** 2021-04-11 05:19 UTC
Labels: bug, compatibility
