### ISSUE TITLE
Keybindngs with []{} don't work on AZERTY keyboards

### ISSUE THREAD

**Issue by EdualcLaiv** [jesseduffield/lazygit#3390] opened 2024-03-16 01:05 UTC
**Describe the bug**

Several keybinds do not work when using a french AZERTY keyboard.

> A specific issue related to #1758.

**To Reproduce**

1. Connect an AZERTY keyboard (or configure your OS to think your key).
2. Opon lazygit.
3. Move to the third panel
4. Type [ or ]
5. The tab stays at "Local branches" and never moves to "Remotes" or "Tags".

**Expected behavior**

- "[" and "]" should move to previous and next tab
- "{" and "}" should decrease and increase the size of the context around changes.

**Version info:**
commit=5e388e21c8ca6aa883dbcbe45c47f6fdd5116815
build date=2023-08-07T14:05:48Z
build source=binaryRelease
version=0.40.2
os=windows
arch=amd64
git version=2.44.0.windows.1

**Additional context**

- I tried it with several keyboards. I can confirm it worked fine on QWERTY with my install but worked with none of my AZERTY keyboards.

- I don't think those specific keybindings can be changed; or I misread the docs.

**Comment by mark2185** [comment] 2024-03-16 11:45
Possible duplicate of https://github.com/jesseduffield/lazygit/issues/3366

Do you need AltGr to write `[` or `]`? Would you kindly try building `master`?

**Comment by EdualcLaiv** [comment] 2024-03-16 18:11
It works when building master.

Sorry for not trying that first and for not seeing it is indeed a duplicate of #3366 (one indeed need altgr to use those keys on azerty).

Thanks.

**Closed** 2024-03-16 19:18 UTC
Labels: bug

**Comment by SimpelMe** [comment] 2025-11-11 21:05
With my mac I normally write `[` or `]` with `opt` + `5` or `opt` + `6`. In lazygit I have to add the `fn` key too. This is true for all characters I write with the `opt` key as far as I tried.
