### ISSUE TITLE
Customize reference branch for colored commit 

### ISSUE THREAD

**Issue by joihn** [jesseduffield/lazygit#2534] opened 2023-03-31 16:25 UTC
## Current feature "colored commit" as it is already implemented:
when you develop on a branch `my_feature`, the commit which are common with `master` are green, the new commit are yellow (very usefull)
![Untitled](https://user-images.githubusercontent.com/11663917/229176863-e969fc55-be4b-4400-8fb9-aa165e703cb2.png)

## Desired improvement:
If wish I could **customize** the reference branch. I wish the commit appears green when they are common with branch `develop` instead of branch `master`) 
**Describe the solution you'd like**
Maybe such a settign could be stored in the global setting file ?
```
setting.yaml:
desired_reference_branch_for_colored_commit: "master" # user can change to "main" to "develop" or etc...
```

**Comment by stefanhaller** [comment] 2023-03-31 16:36
Duplicate of #1062 and #2349

**Comment by jesseduffield** [comment] 2023-04-01 00:05
closing as duplicate

**Closed by jesseduffield** 2023-04-01 00:05 UTC
Labels: enhancement
