### ISSUE TITLE
Support resetting to branch upstream via 'u' menu in branches view

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#2920] opened 2023-08-10 07:52 UTC
**Is your feature request related to a problem? Please describe.**
Currently, in order to reset (hard/mixed/soft) into the upstream branch you need to focus the files view and hit 'g'. This doesn't really make sense, and it means you can't reset onto branches other than the checked out branch.

**Describe the solution you'd like**
We already open up an upstream-related menu when you press 'u' on a branch. I want an option there to reset onto the upstream (keybinding: 'g' for consistency), which itself takes you to a menu showing you the hard/mixed/soft options (similar to what we already have in the files view when you press 'g').

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jesseduffield** [comment] 2023-08-10 07:52
@AzraelSec here's a good one if you want it :)

**Comment by AzraelSec** [comment] 2023-08-10 08:03
@jesseduffield, it works for me! Feel free to assign it to me! :)

**Comment by AzraelSec** [comment] 2023-08-14 06:49
Hey @jesseduffield - I looked into this issue, and I'd like to discuss it with you. The way it's currently implemented matches how git handles the reset command: you can only operate on the branch that is currently checked out (as far as I know). There is no syntax to say `git reset <branch> @{u}`. The only way to do that would be to implement a shortcut that:
1. checks out the target branch
2. resets it
3. checks out the previous branch

I fear that this would result in a very weak approach. Do you have any suggestions? Do you have in mind a more solid implementation for this feature? Thanks!

**Comment by jesseduffield** [comment] 2023-08-16 06:28
Ah sorry, what I meant with this issue was much simpler: we just want to reset the _checked out_ branch onto the selected branch's upstream. For resetting the selected branch onto its own upstream, that would require the user manually checking it out first.

**Comment by peppy** [comment] 2023-08-17 07:22
I'm having a bit of trouble understanding what the use case for this is (we already have a lot of reset options, so I'd like to understand the reason for adding another one).

As far as I can tell, I can already reset the current branch to a selected upstream branch from the branches window:

https://github.com/jesseduffield/lazygit/assets/191335/cdd9e4f9-401b-4b7b-b38c-7360e8312a1b

**Comment by stefanhaller** [comment] 2023-08-17 08:42
I had the same question but didn't dare to ask. 😅 

My take is that this command is really only useful for resetting the checked-out branch to _its own_ upstream. (We already have a way to do that, by hitting `g` in the files panel; the problem is that this might not the most intuitive place to look for it, depending on why you want to reset: if you want to do a hard reset to get rid of your local modifications, then it is, but if you want to reset because your local branch diverged from upstream and you want to put it back, it's not.)

Personally I have never had the need to reset some branch onto _another_ branch's upstream; I'd say in the rare case where you need that, it's ok to require the user to navigate to the remote branches tab and go find the branch there.

**Comment by jesseduffield** [comment] 2023-08-17 13:19
I'm open to a better UX than the one I proposed. I think we can all agree that the existing two approaches for resetting to a branch's upstream are not ideal:
* Resetting to upstream via files view is unintuitive
* Going through the remote branches view is imo too much effort

I want a way to easily reset the current branch to it's upstream via the branches view. My proposal is that you press 'u' to view options related to the selected branch's upstream, and one of those options is to reset the checked out branch into that upstream.

Given that:
* It's rare that you would want to reset onto a random branch's upstream
* If you want to do that, you can go through the remote branches view

, I'm open to a UX that optimises for just the use case of resetting onto the checked out branch's upstream. But in my mind we lose nothing by supporting that flow for any selected branch's upstream (whether it's 'r' 'u' or 'u' 'r' I'm not strongly opinionated)

**Comment by stefanhaller** [comment] 2023-08-17 13:24
I do think that it could be confusing to offer the command for any (non-checkout-out) branch; people might think that this will reset the _selected_ branch onto its upstream, not the current one. We had this confusion in this very PR ([see above](https://github.com/jesseduffield/lazygit/issues/2920#issuecomment-1676771706)).

One option that we could consider is to only show the command if the selected branch is the checked-out one.

**Comment by AzraelSec** [comment] 2023-08-17 22:44
I get @jesseduffield's point (as we are implementing a feature for a specific branch, why don't we implement it generically for all of them?), but I also agree with the others about the risk of confusing the users. I tried to make the operation result as explicit as possible on the menu item, but it could still not be enough.

> One option that we could consider is to only show the command if the selected branch is the checked-out one.

This suggestion would provide a good and more understandable UX, IMHO. We could begin with the suggested implementation and change it in the future based on the users' feedback.

**Closed** 2023-09-06 06:45 UTC
Labels: enhancement, good first issue
