### ISSUE TITLE
Crashed when rewording a commit

### ISSUE THREAD

**Issue by ronen-fr** [jesseduffield/lazygit#1223] opened 2021-04-07 05:31 UTC
Lazygit crashed while I was trying to edit a commit message

**To Reproduce**
1. select a commit
2. 'r' from the menu
3. move around in the commit message
4. paste text to add

**Expected behavior**
Not crashing?

Error message:

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/jesseduffield/gocui.(*View).writeRune(0xc000234580, 0x0, 0x5, 0xc000000000, 0xc13700, 0xc0000e5760)
	/builddir/build/BUILD/lazygit-0.26.1/vendor/github.com/jesseduffield/gocui/edit.go:359 +0x6d9
github.com/jesseduffield/gocui.(*View).EditWrite(0xc000234580, 0x0)
	/builddir/build/BUILD/lazygit-0.26.1/vendor/github.com/jesseduffield/gocui/edit.go:68 +0x6b
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).defaultEditor(0xc00022c000, 0xc000234580, 0x16, 0x1000000000000)
	/builddir/build/BUILD/lazygit-0.26.1/pkg/gui/editors.go:72 +0x185
github.com/jesseduffield/gocui.EditorFunc.Edit(0xc0006b2ad0, 0xc000234580, 0x490016, 0x7fc650c66f00)
	/builddir/build/BUILD/lazygit-0.26.1/vendor/github.com/jesseduffield/gocui/edit.go:27 +0x4b
github.com/jesseduffield/gocui.(*Gui).onKey(0xc00022e240, 0xc00049e660, 0xb23760, 0xc000198101)
	/builddir/build/BUILD/lazygit-0.26.1/vendor/github.com/jesseduffield/gocui/gui.go:871 +0x342
github.com/jesseduffield/gocui.(*Gui).handleEvent(0xc00022e240, 0xc00049e660, 0x3, 0x0)
	/builddir/build/BUILD/lazygit-0.26.1/vendor/github.com/jesseduffield/gocui/gui.go:551 +0x46
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc00022e240, 0xc000000004, 0xc0002d5a98)
	/builddir/build/BUILD/lazygit-0.26.1/vendor/github.com/jesseduffield/gocui/gui.go:499 +0x42a
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc00022c000, 0x0, 0x0)
	/builddir/build/BUILD/lazygit-0.26.1/pkg/gui/gui.go:507 +0x51e
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc00022c000, 0x0, 0xb4c46c)
	/builddir/build/BUILD/lazygit-0.26.1/pkg/gui/gui.go:520 +0x108
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc0002c2380, 0xc0001645a0, 0x0)
	/builddir/build/BUILD/lazygit-0.26.1/pkg/app/app.go:240 +0x6b
main.main()
	/builddir/build/BUILD/lazygit-0.26.1/main.go:126 +0xb3b

**Desktop (please complete the following information):**
 - OS: Fedora33
 - Lazygit Version commit=, build date=, build source=unknown, version=0.26.1, os=linux, arch=amd64

**Comment by jesseduffield** [comment] 2021-04-07 05:32
@ronen-fr could you try this on the latest release?

**Comment by iyzana** [comment] 2021-04-08 11:56
I had the same (very similar?) stacktrace with a similar reproduction (pressing <CTRL-W> in the commit message dialog).
That problem is fixed in 0.27.1

**Comment by Axel-Jacobsen** [comment] 2021-07-22 17:53
I can confirm I am getting this on a fresh install from `brew install jesseduffield/lazygit/lazygit`, 07/22

**Comment by jesseduffield** [comment] 2021-10-17 04:24
should be fixed in https://github.com/jesseduffield/lazygit/pull/1518. Can anybody confirm?

**Comment by jesseduffield** [comment] 2023-04-01 01:04
Closing due to staleness

**Closed by jesseduffield** 2023-04-01 01:04 UTC
Labels: bug
