### ISSUE TITLE
Crash upon Startup with ZSH shortcut: syscall.Errno operation not supported by device

### ISSUE THREAD

**Issue by theniceboy** [jesseduffield/lazygit#1233] opened 2021-04-08 06:14 UTC
**Describe the bug**
Crash on start when using zsh keyboard mapping :
```
2021/04/08 14:10:26 An error occurred! Please create an issue at https://github.com/jesseduffield/lazygit/issues

syscall.Errno operation not supported by device
/home/runner/work/lazygit/lazygit/main.go:133 (0x161cabb)
/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/proc.go:225 (0x10383b6)
/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:1371 (0x106c201)
```
but it works fine by just typing `lazygit` in the terminal

**To Reproduce**
1. Put this in zshrc
```
function openlazygit {
    zle_eval lazygit
}

zle -N openlazygit; bindkey "^G" openlazygit
```
2. Press `ctrl+g` in terminal
3. See error

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.2
 - Lazygit Version 0.27.1 (`commit=a229547048b78fb5130fc5252f696dc8e2d59be4, build date=2021-04-07T13:01:38Z, build source=binaryRelease, version=0.27.1, os=darwin, arch=amd64`)
 - Zsh Version `zsh 5.8 (x86_64-apple-darwin20.0)`

**Comment by jesseduffield** [comment] 2021-04-08 14:13
This would be a result of the switch to tcell. I am not too sure how to get around this: I assume that function previously worked because lazygit could receive all its inputs from stdin? If so, it's possible tcell doesn't work that same way :/

**Comment by theniceboy** [comment] 2021-04-10 12:00
@jesseduffield Sorry I forgot to include the `zle_eval` function! Here it is:
```
function zle_eval {
    echo -en "\e[2K\r"
    eval "$@"
    zle redisplay
}
```

**Comment by theniceboy** [comment] 2021-04-14 16:17
Can confirm that https://github.com/jesseduffield/lazygit/pull/1217 caused the problem

**Comment by zaggerj** [comment] 2021-04-27 09:51
> Can confirm that #1217 caused the problem

have you fixed this problem yet?

**Comment by theniceboy** [comment] 2021-04-28 12:35
> have you fixed this problem yet?

well, aside from switching to a version before when that PR was merged, no, unfortunately.

**Comment by suessflorian** [comment] 2021-06-06 23:07
Is there a temporary work around for this?

**Comment by jesseduffield** [comment] 2021-06-06 23:12
@theniceboy @suessflorian @zaggerj Looks like tcell made some big changes recently. I've bumped tcell on the master branch, and I tried reproducing the error but couldn't (though I didn't attempt to reproduce the error initially so it could be a difference in environment).

Could one of you check to see if the issue is fixed on master, on your end?

**Comment by suessflorian** [comment] 2021-06-06 23:17
Can confirm master has fixed this;

```
function _lazygit { lazygit }
zle -N _lazygit
bindkey "^@" _lazygit
brew uninstall lazygit
git clone https://github.com/jesseduffield/lazygit.git
cd lazygit
go install

# control space now opens lazygit
```

**Comment by suessflorian** [comment] 2021-06-06 23:26
Side note - seems like escape doesn't exit `lazygit` anymore. Mind you should be using `Ctrl-c` to abort anyways.

**Comment by jesseduffield** [comment] 2021-06-06 23:51
That's a default configuration which has changed: because the escape key was used to exit the current context (e.g. a popup, or a sub-panel) it caused problems when people wanted to escape all the way back to the top context without actually exiting. So now the way to quit is ctrl+c or 'q', but you can configure to allow `escape` again (the specific configuration key escapes me now (pun intended))

**Comment by jesseduffield** [comment] 2021-06-07 00:22
At any rate I'll close this issue now :)

**Closed by jesseduffield** 2021-06-07 00:22 UTC
Labels: bug
