### ISSUE TITLE
`e`, "Edit" on Windows does not seem to work

### ISSUE THREAD

**Issue by AndrewSav** [jesseduffield/lazygit#1350] opened 2021-06-03 02:43 UTC
**Describe the bug**
On Windows, pressing `o` on a file opens it (also for editing), pressing `e` on a file on the other hand results in a error, and does not open the file.  See screenshot below for the error.

**To Reproduce**
Steps to reproduce the behaviour:

- Move selection to a file
- Press `e`

**Expected behaviour**

To be honest, I'm not sure how behaviour should be different from `o`. What I do know though, is that I expect not to have a error with Windows integration, may be "not-supported" message on Windows, or disable it (and the help functionality) completely? Or make it synonymous to `o` on Windows?

**Screenshots**
![lazygit00](https://user-images.githubusercontent.com/658865/120578057-4dc86e00-c479-11eb-8fab-2a71c0d3fd54.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Lazygit Version: v0.28.1

**Comment by banjo** [comment] 2021-06-06 09:26
I have the same problem, only that I use nano/micro to open files with the `e` command. It specifies the wrong path on windows it seems, so it won't open the correct file (or any file at all).

![wrong file path](https://i.imgur.com/3sGDFzr.png)

**Comment by mjarkk** [comment] 2021-07-30 17:59
> A simple fix would be wrapping the statement into ". Like so:
C:\Windows\system32\cmd.exe /c "nano \"files/config.yml\""

It sadly not that simple, internally we execute [exec.Command](https://pkg.go.dev/os/exec#Command) that's basically what any shell uses under the hood to execute a program *(the function it equal in almost all languages)*.

The problem is the following:
`exec.Command`'s arguments are the following *(`...string` means any number of strings)*
```go
func Command(name string, arg ...string) *Cmd
```
every `arg` is essentially a quoted string with anything allowed inside (so that's also spaces) and inside of lazygit we execute the above as
```go
exec.Command("cmd.exe", "/c", "nano \\\"files/config.yml\\\"")
```
this is somewhat equal to executing this in the shell:
```go
C:\Windows\system32\cmd.exe "/c" "nano \"files/config.yml\""
```
I hope that explains it :), now for some debugging.

Now there is a problem here and to explain it lets see what the shell will make from the above.
Every space in the shell is a arg so the first 2 are easy
- `C:\Windows\system32\cmd.exe`
- `/c`
Now the 3th is a bit different as it's a as it's an escaped arg, lets un-escape it and lets see what we gets:
- `"nano "files/config.yml"`

Now lets put the above in the go function:
```go
exec.Command("C:\Windows\system32\cmd.exe", "/c", "nano \"files/config.yml\")
```

If you look closely we use an escape (`\`) before the `"` so that's something that could be wrong on our side.
Have already tried remove that extra escape but it has no effect :(

So what now?, confusion, i literally do the same as in the shell but it doesn't works maybe the this writing down of the problem has effect :)

**Comment by AndrewSav** [comment] 2021-07-31 00:55
@mjarkk 

In the `exec.Command` link you quoted, we can read:

> On Windows, processes receive the whole command line as a single string and do their own parsing. Command combines and quotes Args into a command line string with an algorithm compatible with applications using CommandLineToArgvW (which is the most common way). Notable exceptions are msiexec.exe and cmd.exe (and thus, all batch files), which have a different unquoting algorithm. In these or other similar cases, you can do the quoting yourself and provide the full command line in SysProcAttr.CmdLine, leaving Args empty.

This is what's missing in the code, IMO: we should either not use `cmd.exe` or we should leave `Args` empty if we do, because other wise the quoting that golang does for us does not work.

**Comment by fsmiamoto** [comment] 2021-08-01 17:03
Maybe @Ryooooooga could help with this one, he helped me a lot regarding quoting and escaping.

**Comment by Ryooooooga** [comment] 2021-08-02 10:40
@mjarkk (or someone)

related PR: https://github.com/jesseduffield/lazygit/pull/1173, https://github.com/jesseduffield/lazygit/pull/1308

There's a bit of a circumstance to this strange behavior about escapes and backslashes (and the resulting errors).

> It sadly not that simple, internally we execute exec.Command that's basically what any shell uses under the hood to execute a program (the function it equal in almost all languages).

Yes. And `exec.Command` is built by `OSCommand.ExecutableFromString`.
Almost all commands in lazygit are executed through `OSCommand.ExecutableFromString`.

https://github.com/jesseduffield/lazygit/blob/d626bcac0029267d3f45223198902f5cb78d9dc1/pkg/commands/oscommands/os.go#L194-L199

For example, [`OSCommand.OpenFile`](https://github.com/jesseduffield/lazygit/blob/f8f596d097942d0a0e0cd0ab76e48ec1c2471d75/pkg/commands/oscommands/os.go#L301-L316) (`o` key)　discussed in https://github.com/jesseduffield/lazygit/pull/1308 is the exactly that.

In `ExecutableFromString`, the passed command string is split by [`str.ToArgv`](https://github.com/mgutz/str/blob/968bf66e3da857419e4f6e71b2d5c9ae95682dc4/funcsPZ.go#L274-L381).
However, in short, the behavior of `str.ToArgv` on Windows is strange (it's hard to explain how it's strange in simple terms, so just read the code).
This is why Linux and macOS only need to enclose file names with `"` when quoting them, but Windows needs to do with `\"`.

<details>
<summary>Implementation of <code>OSCommand.Quote</code></summary>

mac/Linux:
https://github.com/jesseduffield/lazygit/blob/d626bcac0029267d3f45223198902f5cb78d9dc1/pkg/commands/oscommands/os_default_platform.go#L15

Windows:
https://github.com/jesseduffield/lazygit/blob/d626bcac0029267d3f45223198902f5cb78d9dc1/pkg/commands/oscommands/os_windows.go#L9

https://github.com/jesseduffield/lazygit/blob/d626bcac0029267d3f45223198902f5cb78d9dc1/pkg/commands/oscommands/os.go#L347-L360

</details>

Enclosing with `\"` may seem wrong, but it works correctly when used with `str.ToArgv`.

---

However, it turns out that [`Gui.editFile`](https://github.com/jesseduffield/lazygit/blob/53ea7df655a8d4893fa623a65d16c7bffded779b/pkg/gui/files_panel.go#L476-L485) (`e` key) does not call `OSCommand.ExecutableFromString` (unlike `OSCommand.OpenFile`).

The command string constructed by `GitCommand.EditFileCmdStr` is passed directly to `exec.Command` via [`OSCommand.PrepareShellSubProcess`](https://github.com/jesseduffield/lazygit/blob/53ea7df655a8d4893fa623a65d16c7bffded779b/pkg/commands/oscommands/os.go#L326-L340) (without `str.ToArgv`).

https://github.com/jesseduffield/lazygit/blob/53ea7df655a8d4893fa623a65d16c7bffded779b/pkg/commands/files.go#L349

```go
// if
editor = "vi"
filename = "FILE"
// then ↓
return `vi "FILE"`   // mac/Linux
return `vi \"FILE\"` // Windows

// finally
exec.Command("bash", "-c", `vi "FILE"`)   // mac/Linux
exec.Command("cmd", "/c", `vi \"FILE\"`)  // Windows
```

In this case, I think we should call [`OSCommand.ShellCommandFromString`](https://github.com/jesseduffield/lazygit/blob/53ea7df655a8d4893fa623a65d16c7bffded779b/pkg/commands/oscommands/os.go#L201-L213) instead of `OSCommand.PrepareShellSubProcess`.

(I don't have a Windows PC right now, so I don't know if this is correct)

**Comment by mjarkk** [comment] 2021-08-18 11:59
@AndrewSav is this fixed in the last release for you?

**Comment by AndrewSav** [comment] 2021-08-19 03:23
> @AndrewSav is this fixed in the last release for you?

No, it trying to open "{{filename}}" I do not have the file with this exact name in my file system. It should open the current file (in lazygit) instead.

**Comment by AndrewSav** [comment] 2021-08-19 03:34
> @AndrewSav is this fixed in the last release for you?

@mjarkk Unfortunately, no. Here are some screenshots:

![lg01](https://user-images.githubusercontent.com/658865/130003352-3d59673d-1666-48e9-b8e8-2b4f3558b98e.png)
![lg02](https://user-images.githubusercontent.com/658865/130003382-32080c23-fbaf-4ea5-b734-dc227bef7743.png)
![lg03](https://user-images.githubusercontent.com/658865/130003405-9550d498-adbf-43c8-9b1a-9c783bba3a4a.png)

**Comment by Ryooooooga** [comment] 2021-08-23 12:26
@AndrewSav This issue seems to have been resolved in https://github.com/jesseduffield/lazygit/pull/1413.

**Comment by jesseduffield** [comment] 2021-10-17 09:31
Thanks @Ryooooooga ! Closing now

**Closed by jesseduffield** 2021-10-17 09:31 UTC
Labels: bug

**Comment by jesseduffield** [comment] 2021-10-20 22:29
@AndrewSav thanks for the feedback. I wonder how other projects manage this. Maybe there's a way to add a label of `v0.30` and when a release of that name comes out, a bot closes the issue.
