### ISSUE TITLE
Horizonal split for main panel layout split (When only 2 panes are displayed)

### ISSUE THREAD

**Issue by vignesh0025** [jesseduffield/lazygit#2364] opened 2023-01-15 06:14 UTC
**Is your feature request related to a problem? Please describe.**
When zoomed in to two column layout, most infortant information is hidden in the left panel e.g. in commits view as shown below.

![Screenshot from 2023-01-15 11-35-02](https://user-images.githubusercontent.com/60247919/212525525-5862c270-ea95-4824-a641-1150562b89fb.png)

**Describe the solution you'd like**
We need an option to change the split to vertical mode (or simply rotate the view to horizondal split) as shown below. This lets us see the full commit message as well as commit details.
```
|==================|
|                  |
|   Commit Graph   |
|                  |
|==================|
|                  |
|   Commit Detail  |
|                  |
|==================|
```

**Describe alternatives you've considered**
I was thinking gui.mainPanelSplitMode does this but it seems to be different from what  I thought it does.

**Comment by mark2185** [comment] 2023-01-15 07:39
Duplicate of #1962 and #2299 .

**Closed by mark2185** 2023-01-15 07:39 UTC
Labels: enhancement
