### ISSUE TITLE
Crashes when using menu

### ISSUE THREAD

**Issue by voigtan** [jesseduffield/lazygit#1014] opened 2020-09-24 08:53 UTC
**Describe the bug**
Application crashes when Im navigating in the menu

**To Reproduce**
1. Open the Menu with `x` and press `x` again
2. Click on `close menu`

When I do this the client crashes and give me this message:

```
*errors.errorString unknown view
/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:290 (0x160f104)
/home/runner/work/lazygit/lazygit/pkg/gui/menu_panel.go:44 (0x1687774)
/home/runner/work/lazygit/lazygit/pkg/gui/options_menu_panel.go:52 (0x16aa2d2)
/home/runner/work/lazygit/lazygit/pkg/gui/menu_panel.go:99 (0x1687ea8)
/home/runner/work/lazygit/lazygit/pkg/gui/view_helpers.go:353 (0x16af046)
/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:909 (0x1611e9b)
/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:889 (0x1611eab)
/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:809 (0x1611c4f)
/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:497 (0x16100f2)
/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:457 (0x16100fd)
/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:455 (0x165eaf7)
/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:465 (0x165ee14)
/home/runner/work/lazygit/lazygit/pkg/app/app.go:222 (0x16b9d3b)
/home/runner/work/lazygit/lazygit/main.go:70 (0x16bafa3)
/opt/hostedtoolcache/go/1.14.9/x64/src/runtime/proc.go:203 (0x1034eda)
/opt/hostedtoolcache/go/1.14.9/x64/src/runtime/asm_amd64.s:1373 (0x10625b1)
```

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Lazygit Version 0.22.8 (but also had this behavior on the previous version)

**Additional context**
I asked a friend that also uses lazygit and he cant reproduce this error.

I installed lazygit via brew with ```brew install jesseduffield/lazygit/lazygit```

I do have a theory why this could have happend to my setup, I used the menu inside lazygit to see if there was an update and it was updated and I started to have other issues with that version so I had issues trying to reinstall it with brew. Is there a easy way to remove everything and re-install a clean version of lazygit?

**Comment by sagor999** [comment] 2020-09-24 22:04
Using same version, but getting similar crash when pushing into branch:
```
2020/09/24 15:03:20 An error occurred! Please create an issue at https://github.com/jesseduffield/lazygit/issues

*errors.errorString unknown view
/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:301 (0xa0d282)
/home/runner/work/lazygit/lazygit/pkg/gui/context.go:479 (0xa4f2e0)
/home/runner/work/lazygit/lazygit/pkg/gui/context.go:414 (0xaa2ec6)
/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:461 (0xa0e213)
/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:455 (0xa5cf07)
/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:465 (0xa5d224)
/home/runner/work/lazygit/lazygit/pkg/app/app.go:222 (0xab814b)
/home/runner/work/lazygit/lazygit/main.go:70 (0xab93b3)
/opt/hostedtoolcache/go/1.14.9/x64/src/runtime/proc.go:203 (0x43593a)
/opt/hostedtoolcache/go/1.14.9/x64/src/runtime/asm_amd64.s:1373 (0x4631d1)
```
Version:
```
commit=307d051ec2ec03a2fcd347ce94f205aa2dca75fc, build date=2020-09-18T11:04:08Z, build source=binaryRelease, version=0.22.8, os=linux, arch=amd64
```

**Comment by jesseduffield** [comment] 2020-09-26 01:57
@voigtan I was able to reproduce the error, and I've fixed the issue in this PR: https://github.com/jesseduffield/lazygit/pull/1017

@sagor999 I couldn't reproduce your error. Could you see if https://github.com/jesseduffield/lazygit/pull/1018 fixes the issue for you?

**Comment by sagor999** [comment] 2020-09-26 02:50
@jesseduffield it doesn't happen very often. Maybe once a day. So very hard to repro. :(

**Comment by jesseduffield** [comment] 2020-09-26 09:34
@sagor999 at any rate I've gone ahead and merged the PR. I'm going to close this issue but if you get that stacktrace again when working off the master branch please open another issue for it :)

**Closed by jesseduffield** 2020-09-26 09:34 UTC
Labels: bug
