### ISSUE TITLE
Support git bare repository

### ISSUE THREAD

**Issue by vbauerster** [jesseduffield/lazygit#846] opened 2020-05-16 08:09 UTC
I have a git bare repository created with `git init --bare $HOME/.myconf`. While invoking `lazygit` from the bare repository, following error occurs. With plain `git` it's possible to pass work tree separately with `--work-tree=<path>`. Can you please support same option for `lazygit`?

```
2020/05/16 12:20:30 An error occurred! Please create an issue at https://github.com/jesseduffield/lazygit/issues

*errors.errorString fatal: this operation must be run in a work tree

/private/tmp/lazygit-20200513-82362-1d0vovy/lazygit-0.20.3/pkg/commands/os.go:187 (0x1628903)
/private/tmp/lazygit-20200513-82362-1d0vovy/lazygit-0.20.3/pkg/commands/os.go:98 (0x1627ef2)
/private/tmp/lazygit-20200513-82362-1d0vovy/lazygit-0.20.3/pkg/commands/os.go:153 (0x16ab6cd)
/private/tmp/lazygit-20200513-82362-1d0vovy/lazygit-0.20.3/pkg/app/app.go:133 (0x16ab693)
/private/tmp/lazygit-20200513-82362-1d0vovy/lazygit-0.20.3/pkg/app/app.go:116 (0x16ab3e2)
/private/tmp/lazygit-20200513-82362-1d0vovy/lazygit-0.20.3/main.go:67 (0x16ac89b)
/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/proc.go:203 (0x1036ea2)
        main: fn()
/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/asm_amd64.s:1373 (0x1064691)
        goexit: BYTE    $0x90   // NOP
```

**Comment by jesseduffield** [comment] 2020-08-25 11:29
@vbauerster could you give this PR a go to see if it resolves your issue: https://github.com/jesseduffield/lazygit/pull/972

It allows you to pass the `--work-tree=<path>` arg to lazygit.

**Comment by vbauerster** [comment] 2020-08-25 14:08
It didn't work. There was no any output, so I had to press ctrl c to get back to my prompt. Probably I should mention before, full git command I use is `git --git-dir=$HOME/.myconf --work-tree=$HOME`. It is for tracking my [dotfiles](https://github.com/vbauerster/myconf).

**Comment by vbauerster** [comment] 2020-08-26 12:15
Maybe this [post](https://news.ycombinator.com/item?id=11070797) can help.

**Comment by jesseduffield** [comment] 2020-09-27 05:44
closing as a duplicate of https://github.com/jesseduffield/lazygit/issues/778 but do not fret, The feature is almost done https://github.com/jesseduffield/lazygit/pull/1023

**Closed** 2020-09-27 05:45 UTC
Labels: enhancement
