### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by mia0x75** [jesseduffield/lazygit#329] opened 2018-11-22 02:12 UTC
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*escapeInterpreter).parseOne(0xc000370000, 0x33, 0xc00094b901, 0x0, 0x0)
	/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/escape.go:116 +0x673
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*View).parseInput(0xc000355500, 0xc000000033, 0x0, 0x0, 0x0)
	/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/view.go:258 +0x61
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*View).Write(0xc000355500, 0xc0010ca000, 0x43dd8, 0x44000, 0x1177, 0xc00094ba30, 0x40b198)
	/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/view.go:236 +0x25d
fmt.Fprint(0xe7cde0, 0xc000355500, 0xc00094ba98, 0x1, 0x1, 0x0, 0x0, 0xc0000ac300)
	/usr/lib/golang/src/fmt/print.go:223 +0x8b
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshFiles(0xc0002b24e0, 0xc0002823f0, 0x23, 0x0)
	/src/github.com/jesseduffield/lazygit/pkg/gui/files_panel.go:334 +0x14b
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handleFilePress(0xc0002b24e0, 0xc0002823f0, 0xc000355500, 0xc00094bc94, 0x2)
	/src/github.com/jesseduffield/lazygit/pkg/gui/files_panel.go:67 +0x115
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handleFilePress-fm(0xc0002823f0, 0xc000355500, 0x1, 0x0)
	/src/github.com/jesseduffield/lazygit/pkg/gui/keybindings.go:144 +0x3e
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybinding(0xc0002823f0, 0xc000355500, 0xc000366210, 0x1, 0xc000334228, 0xc00094bc94)
	/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:703 +0x3e
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc0002823f0, 0xc000355500, 0xc00094bca0, 0x9933ea, 0x0, 0x0)
	/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:689 +0xef
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).onKey(0xc0002823f0, 0xc00094bca0, 0xc000364500, 0xc0002c0390)
	/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:650 +0x1b0
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).handleEvent(0xc0002823f0, 0xc00094bca0, 0x2, 0x0)
	/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:431 +0x40
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0002823f0, 0xc0002823f0, 0x0)
	/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:391 +0x2d2
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc0002b24e0, 0x0, 0x0)
	/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:403 +0x2b1
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc0002b24e0)
	/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:412 +0x2f
main.main()
	/src/github.com/jesseduffield/lazygit/main.go:53 +0x12a

git version: commit b9ecb82cb7ea5be027ebfcfa33ad45287e08c5f7

**Comment by jesseduffield** [comment] 2018-11-23 02:56
I've been able to replicate this by increasing the frequency of refreshFiles to running every 20 milliseconds, and then mashing the space button on an unstaged file to toggle it back and forth between staged and unstaged. I've looked at the code in parseOne() and the issue is really weird: I can put a check for the length right before we access it and it will pass the check but then fail when it actually tried to access the array index, so it's possible that the reset() method is being called on the escape interpreter and getting the array emptied inbetween. I don't really know what's going on with the escape interpreter but it looks like it's a race condition.

Maybe it wouldn't be that hard to add a mutex here, but it's gonna require some deeper investigation as to how it all works in the first place.

**Comment by gabstv** [comment] 2019-04-10 00:43
Happening with `commit=, build date=, build source=homebrew, version=0.7.2, os=darwin, arch=amd64`
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handleCreateRebaseOptionsMenu.func1(0x5, 0x1000000000040, 0x0)
	/private/tmp/lazygit-20190404-25553-rwbozq/lazygit-0.7.2/src/github.com/jesseduffield/lazygit/pkg/gui/rebase_options_panel.go:30 +0x71
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).createMenu.func1(0xc00026c090, 0xc00031a500, 0x4, 0xc00050fc01)
	/private/tmp/lazygit-20190404-25553-rwbozq/lazygit-0.7.2/src/github.com/jesseduffield/lazygit/pkg/gui/menu_panel.go:71 +0x51
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybinding(...)
	/private/tmp/lazygit-20190404-25553-rwbozq/lazygit-0.7.2/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:719
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc00026c090, 0xc00031a500, 0xc00050fc58, 0x20800000000, 0xb, 0xc)
	/private/tmp/lazygit-20190404-25553-rwbozq/lazygit-0.7.2/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:705 +0x102
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).onKey(0xc00026c090, 0xc00050fc58, 0x2, 0x0)
	/private/tmp/lazygit-20190404-25553-rwbozq/lazygit-0.7.2/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:666 +0x13e
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).handleEvent(...)
	/private/tmp/lazygit-20190404-25553-rwbozq/lazygit-0.7.2/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:447
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc00026c090, 0xc00026c090, 0x0)
	/private/tmp/lazygit-20190404-25553-rwbozq/lazygit-0.7.2/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:407 +0x203
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc000338000, 0x0, 0x0)
	/private/tmp/lazygit-20190404-25553-rwbozq/lazygit-0.7.2/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:593 +0x367
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc000338000, 0xc0001d48c0, 0xc00014a0f0)
	/private/tmp/lazygit-20190404-25553-rwbozq/lazygit-0.7.2/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:602 +0x2f
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc0001d48c0, 0xc0002761c0, 0xc0001d48c0)
	/private/tmp/lazygit-20190404-25553-rwbozq/lazygit-0.7.2/src/github.com/jesseduffield/lazygit/pkg/app/app.go:130 +0x6b
main.main()
	/private/tmp/lazygit-20190404-25553-rwbozq/lazygit-0.7.2/src/github.com/jesseduffield/lazygit/main.go:51 +0x428
```

**Comment by jesseduffield** [comment] 2019-04-10 00:46
@gabstv these appear to be quite different stack traces. Could you please create a separate issue for this?

**Comment by jesseduffield** [comment] 2020-01-12 03:01
should be fixed in https://github.com/jesseduffield/lazygit/pull/592

**Closed by jesseduffield** 2020-01-12 03:01 UTC
