### ISSUE TITLE
error "expected section name"

### ISSUE THREAD

**Issue by lobneroO** [jesseduffield/lazygit#3513] opened 2024-04-22 13:22 UTC
**Describe the bug**
When opening a specific repository with lazygit in powershell, lazygit opens with an error
> 52:3: expected section name

Then, in Git-Bash the TUI quickly disappears and is replaced by characters running through on the right side. In powershell it slowly builds up the commits section (while the error is displayed) and then there, too, the TUI is replaced by the character run through (in the second video in powershell, this starts at ~1:47):

Git-Bas:
https://github.com/jesseduffield/lazygit/assets/17877050/666e1b4b-445e-4b90-93d3-61d7f35f5f9d

Powershell:
https://github.com/jesseduffield/lazygit/assets/17877050/36081d5e-4aa7-464a-952f-2d9356c2f084

At this point, I have to kill the console tab, because neither ctrl+c nor q close this.

I'm pretty sure this repository had worked before and it certainly works on a different PC. On this PC it is installed via chocolatey, on the one where it is working right now it was installed via winget. It is up to date on the error one (at least choco upgrade said it was).

I tried a different repository, that one works on both PCs. Neither repo is open source though, sorry.

**To Reproduce**

1. open lazygit in an affected repository...

**Expected behavior**
No errors appear, TUI stays open

**Screenshots**

**Version info:**
_Run `lazygit --version` and paste the result here_
> lazygit --version
commit=3675570a391b1a49ddd198b4c7e71e17701d4404, build date=2024-03-23T09:09:11Z, build source=binaryRelease, version=0.41.0, os=windows, arch=amd64, git version=2.44.0.windows.1

_Run `git --version` and paste the result here_
> git version 2.44.0.windows.1

on the second PC on which it does not crash:
_Run `lazygit --version` and paste the result here_
> commit=5e388e21c8ca6aa883dbcbe45c47f6fdd5116815, build date=2023-08-07T14:05:48Z, build source=binaryRelease, version=0.40.2, os=windows, arch=amd64, git version=2.41.0.windows.1

_Run `git --version` and paste the result here_
> git version 2.41.0.windows.1

**Additional context**
Windows 11
Windows Terminal
Powershell + Git-Bash

# Debug/Logs
I tried the suggested `lazygit --debug` / `--logs` combo. The logs did not change. The output I got was:

> Apr 22 15:19:01 |INFO| refreshing all scopes in async mode
> Apr 22 15:19:01 |INFO| Refresh took 0s
> Apr 22 15:19:01 |ERRO| ignoring create popup panel because a popup panel is already open
> Apr 22 15:19:01 |DEBU| RunCommand command="git stash list -z --pretty=%ct|%gs"
> Apr 22 15:19:01 |INFO| refreshing all scopes in async mode
> Apr 22 15:19:01 |INFO| Refresh took 0s
> Apr 22 15:19:01 |ERRO| ignoring create popup panel because a popup panel is already open
> Apr 22 15:19:01 |INFO| refreshing all scopes in async mode
> Apr 22 15:19:01 |INFO| Refresh took 0s
> Apr 22 15:19:01 |ERRO| ignoring create popup panel because a popup panel is already open

**Comment by stefanhaller** [comment] 2024-04-22 14:15
I suspect there's something wrong with this repo's `.git/config` file, probably at line 52. Have a look if there's any junk in there.

I'm only guessing here though, couldn't reproduce the problem on my end, at least not with the symptoms you saw.

**Comment by lobneroO** [comment] 2024-04-23 06:15
Yes, that seems to have been the problem. There was a junk entry there:

```
[ ""]
	local = user.email
```

For me this solved now. If you consider it done, feel free to close, but I'll leave it open if you want to add a fix for it in lazygit.
Thank you.

**Comment by stefanhaller** [comment] 2024-04-23 06:58
On master it no longer misbehaves in the way you described, because of [this commit](https://github.com/jesseduffield/lazygit/commit/bbad3a70). However, now you get no indication whatsoever that there's something wrong (unless you have logging enabled and look at the debug log), so that's also not good. I'd say that's a separate issue though, so I'll close this one.

**Closed by stefanhaller** 2024-04-23 06:58 UTC
Labels: bug
