### ISSUE TITLE
Arch Linux (AUR) package

### ISSUE THREAD

**Issue by fuero** [jesseduffield/lazygit#64] opened 2018-08-07 11:56 UTC
FYI, I've created an AUR package:

https://aur.archlinux.org/packages/lazygit-git/

**Comment by dawidd6** [comment] 2018-08-07 12:29
Hehe, i knew someone will make an AUR package soon and here we are, good job @fuero.

**Comment by frealgagu** [comment] 2018-08-09 14:22
I've added a pull request to add information about arch linux packages in README.md

https://github.com/jesseduffield/lazygit/pull/98

**Comment by nikolowry** [comment] 2018-08-09 18:14
Disclaimer: Not a Go dev and very limited knowledge of the language and packaging system.

Regardless, I just got the following error when trying to install `lazygit-git`:

```
==> Starting build()...
commits_panel.go:6:2: cannot find package "github.com/fatih/color" in any of:
	/usr/lib/go/src/github.com/fatih/color (from $GOROOT)
	/home/neeks/go/src/github.com/fatih/color (from $GOPATH)
gui.go:15:2: cannot find package "github.com/golang-collections/collections/stack" in any of:
	/usr/lib/go/src/github.com/golang-collections/collections/stack (from $GOROOT)
	/home/neeks/go/src/github.com/golang-collections/collections/stack (from $GOPATH)
branches_panel.go:7:2: cannot find package "github.com/jesseduffield/gocui" in any of:
	/usr/lib/go/src/github.com/jesseduffield/gocui (from $GOROOT)
	/home/neeks/go/src/github.com/jesseduffield/gocui (from $GOPATH)
==> ERROR: A failure occurred in build().
    Aborting...
```

---

The `lazygit` AUR package, https://aur.archlinux.org/packages/lazygit, did successfully install

**Comment by fuero** [comment] 2018-08-10 11:30
@nikolowry Sorry, I can't reproduce this, I've built it in a chroot (with `extra-x86_64-build`) and it compiles successfully.

**Comment by fuero** [comment] 2018-08-10 12:01
I've updated my package to point to the master branch and to include the suggestions from https://github.com/jesseduffield/lazygit/issues/74.

@nikolowry:
Sorry, I can't reproduce this. I've compiled it in a chroot (with `extra-x86_64-build -c`), and it works fine.

**Comment by nikolowry** [comment] 2018-08-10 15:43
@fuero myself and Veras (AUR comment) both couldn't build because those three packages weren't found on our systems.

I don't know GO best practices for building w external dependencies that can't be found in the user's PATH, but it should be handled.

I'll try to install again the next time in near my PC.

---

Oh and could add `provides` and/or `conflicts` with `lazygit`? I'm not 100% sure on best practices for declaring your package is a variation of another, so you should refer to the wiki

**Comment by flamendless** [comment] 2018-08-10 17:52
@fuero thanks. I prefer the aur than go packages

**Comment by fuero** [comment] 2018-08-10 17:52
@nikolowry let's continue this in private or on AUR, no need to bother the lazygit folks with this - you'll find my mail address on AUR.

**Comment by Azulinho** [comment] 2018-08-12 20:11
arch user here, works on my machine

**Comment by jesseduffield** [comment] 2018-08-16 11:32
closing as it looks like the issue is resolved. Thanks again @fuero for making the package!

**Closed by jesseduffield** 2018-08-16 11:32 UTC
