### ISSUE TITLE
--work-tree/git-dir command not working in 0.40.0

### ISSUE THREAD

**Issue by MalteFinnern** [jesseduffield/lazygit#2900] opened 2023-08-07 11:18 UTC
**Describe the bug**
As of the last update (0.40.0) the --work-tree and --git-dir option does not work anymore, on start the following messages occures.

`*errors.errorString Error getting repo paths: failed to get worktree git dir path: stat /Users/$my-user$/.git: no such file or directory
github.com/jesseduffield/lazygit/pkg/commands/git.go:100 (0x104589288)
github.com/jesseduffield/lazygit/pkg/gui/gui.go:271 (0x1046ab0f0)
`

**To Reproduce**

git-directory under $HOME/.cfg
working-directy $HOME

starting lazygit with: `lazygit -g $HOME/.cfg/ -w $HOME  ` , above error occures.
using 
 `git --git-dir=$HOME/.cfg/ --work-tree=$HOME/ status `, works as expected

my suspicion: the new work-tree features tries to load the work-tree under $HOME/.git ignoring the "--git-dir" flag.

**Expected behavior**
The -g and -w flag should work, as on the git command.

**Version info:**
commit=, build date=, build source=homebrew, version=0.40.0, os=darwin, arch=arm64, git version=2.41.0

**Additional context**
MacOs M2 Notebook

**Comment by jesseduffield** [comment] 2023-08-07 11:48
Duplicate of https://github.com/jesseduffield/lazygit/issues/2880

I'm looking into this now: I'll leave a comment on the other issue

**Closed by jesseduffield** 2023-08-07 11:48 UTC
Labels: bug
