### ISSUE TITLE
FR: gentler failure with old git versions

### ISSUE THREAD

**Issue by psanan** [jesseduffield/lazygit#784] opened 2020-04-10 20:34 UTC
**Is your feature request related to a problem? Please describe.**
I love lazygit  because it works on most machines I have access to. However, these have various versions of git, which  means that some of the functionality of lazygit (e.g. the cool rebasing stuff) doesn't work everywhere.

**Describe the solution you'd like**
One or both of:

* A minimum/recommended version of git (in the simplest case, the one used to develop/test that release of lazygit) specified somewhere.
* Error messages if I try something that requires a newer Git than I have.

**Describe alternatives you've considered**
I can upgrade git, perform the operation on another machine, or do it the old way (e.g. `git rebase -i`).

**Example**
I want to edit a commit message in the editor, but I have git 2.17, so I see
```
+ git rebase --interactive --autostash --keep-empty --rebase-merges b98a8dbea330e37c37df19cb926f2477649d5016

error: unknown option `rebase-merges'
```
That's not so bad, but I've also had cases where lazygit just hangs forever, and I have to kill it and end up in the middle of a rebase/cherry-pick/etc.

**Comment by jesseduffield** [comment] 2020-08-27 11:53
I've removed the --rebase-merges flag so now you should no longer get that error, however I'm not able to reproduce the issues of freezing. Could you raise a separate issue for that with repro steps?

As for showing a required minimum version, I'll cover that as part of https://github.com/jesseduffield/lazygit/issues/756

Closing :)

**Closed by jesseduffield** 2020-08-27 11:53 UTC
Labels: enhancement, git-version

**Comment by psanan** [comment] 2020-08-27 12:02
Thanks! I'll open an issue when I run into the freezing again and can provide concrete reproduction steps. It hasn't happened for a while, probably due to some combination of avoiding certain features and updating lazygit and/or git on the machines in question.
