### ISSUE TITLE
lazygit-0.27.1 arbitrary crushes on start

### ISSUE THREAD

**Issue by band-a-prend** [jesseduffield/lazygit#1230] opened 2021-04-07 20:31 UTC
Both lazygit-0.27 and lazygit-0.27.1 crushes on start from time to time on trying to launch.
Both 0.27.x versions were built with Go 1.16.2 (Gentoo `dev-lang/go-1.1.6.2`).

The lazygit-0.27.1 output:
```
$ lazygit 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x99f1d3]

goroutine 1 [running]:
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*View).Name(...)
        /var/tmp/portage/dev-vcs/lazygit-0.27.1/work/lazygit-0.27.1/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/view.go:350
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).getWindowForView(...)
        /var/tmp/portage/dev-vcs/lazygit-0.27.1/work/lazygit-0.27.1/src/github.com/jesseduffield/lazygit/pkg/gui/window.go:25
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).currentWindow(...)
        /var/tmp/portage/dev-vcs/lazygit-0.27.1/work/lazygit-0.27.1/src/github.com/jesseduffield/lazygit/pkg/gui/window.go:37
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).getMidSectionWeights(0xc000106a80, 0xc000245518, 0x453c47)
        /var/tmp/portage/dev-vcs/lazygit-0.27.1/work/lazygit-0.27.1/src/github.com/jesseduffield/lazygit/pkg/gui/arrangement.go:42 +0x153
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).getWindowDimensions(0xc000106a80, 0xc000150e40, 0x1d, 0x0, 0x0, 0xa4)
        /var/tmp/portage/dev-vcs/lazygit-0.27.1/work/lazygit-0.27.1/src/github.com/jesseduffield/lazygit/pkg/gui/arrangement.go:136 +0x5e
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).layout(0xc000106a80, 0xc000106c00, 0x0, 0xc000204a80)
        /var/tmp/portage/dev-vcs/lazygit-0.27.1/work/lazygit-0.27.1/src/github.com/jesseduffield/lazygit/pkg/gui/layout.go:48 +0x16d
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.ManagerFunc.Layout(0xc00025c420, 0xc000106c00, 0x30, 0x0)
        /var/tmp/portage/dev-vcs/lazygit-0.27.1/work/lazygit-0.27.1/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:555 +0x30
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).flush(0xc000106c00, 0x0, 0x0)
        /var/tmp/portage/dev-vcs/lazygit-0.27.1/work/lazygit-0.27.1/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:669 +0x45d
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc000106c00, 0xc000000004, 0xc000245a18)
        /var/tmp/portage/dev-vcs/lazygit-0.27.1/work/lazygit-0.27.1/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:614 +0x21d
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc000106a80, 0x0, 0x0)
        /var/tmp/portage/dev-vcs/lazygit-0.27.1/work/lazygit-0.27.1/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:529 +0x51b
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunAndHandleError.func1(0xc000106a01, 0xc000102660)
        /var/tmp/portage/dev-vcs/lazygit-0.27.1/work/lazygit-0.27.1/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:537 +0x45
github.com/jesseduffield/lazygit/pkg/utils.SafeWithError(0xc000245b50, 0x0, 0x0)
        /var/tmp/portage/dev-vcs/lazygit-0.27.1/work/lazygit-0.27.1/src/github.com/jesseduffield/lazygit/pkg/utils/utils.go:380 +0x62
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunAndHandleError(0xc000106a80, 0x0, 0xb6b79f)
        /var/tmp/portage/dev-vcs/lazygit-0.27.1/work/lazygit-0.27.1/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:536 +0x7d
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc0002281c0, 0xc0001de630, 0x0)
        /var/tmp/portage/dev-vcs/lazygit-0.27.1/work/lazygit-0.27.1/src/github.com/jesseduffield/lazygit/pkg/app/app.go:242 +0x6b
main.main()
        /var/tmp/portage/dev-vcs/lazygit-0.27.1/work/lazygit-0.27.1/src/github.com/jesseduffield/lazygit/main.go:126 +0xb3b
```

The lazygit-0.27 output:
```
$ lazygit 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x99f1d3]

goroutine 1 [running]:
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*View).Name(...)
        /var/tmp/portage/dev-vcs/lazygit-0.27/work/lazygit-0.27/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/view.go:350
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).getWindowForView(...)
        /var/tmp/portage/dev-vcs/lazygit-0.27/work/lazygit-0.27/src/github.com/jesseduffield/lazygit/pkg/gui/window.go:25
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).currentWindow(...)
        /var/tmp/portage/dev-vcs/lazygit-0.27/work/lazygit-0.27/src/github.com/jesseduffield/lazygit/pkg/gui/window.go:37
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).getMidSectionWeights(0xc000082f00, 0xc00024d508, 0x453c47)
        /var/tmp/portage/dev-vcs/lazygit-0.27/work/lazygit-0.27/src/github.com/jesseduffield/lazygit/pkg/gui/arrangement.go:42 +0x153
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).getWindowDimensions(0xc000082f00, 0xc000032160, 0x1d, 0x0, 0x0, 0xa4)
        /var/tmp/portage/dev-vcs/lazygit-0.27/work/lazygit-0.27/src/github.com/jesseduffield/lazygit/pkg/gui/arrangement.go:136 +0x5e
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).layout(0xc000082f00, 0xc000083080, 0x0, 0xc00020ca80)
        /var/tmp/portage/dev-vcs/lazygit-0.27/work/lazygit-0.27/src/github.com/jesseduffield/lazygit/pkg/gui/layout.go:48 +0x16d
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.ManagerFunc.Layout(0xc00042e160, 0xc000083080, 0x30, 0xc00046b860)
        /var/tmp/portage/dev-vcs/lazygit-0.27/work/lazygit-0.27/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:555 +0x30
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).flush(0xc000083080, 0x0, 0x0)
        /var/tmp/portage/dev-vcs/lazygit-0.27/work/lazygit-0.27/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:669 +0x45d
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc000083080, 0xc000000004, 0xc00024da18)
        /var/tmp/portage/dev-vcs/lazygit-0.27/work/lazygit-0.27/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:614 +0x21d
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc000082f00, 0x0, 0x0)
        /var/tmp/portage/dev-vcs/lazygit-0.27/work/lazygit-0.27/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:538 +0x53e
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunAndHandleError.func1(0xc000082f01, 0xc00008e660)
        /var/tmp/portage/dev-vcs/lazygit-0.27/work/lazygit-0.27/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:546 +0x45
github.com/jesseduffield/lazygit/pkg/utils.SafeWithError(0xc00024db50, 0x0, 0x0)
        /var/tmp/portage/dev-vcs/lazygit-0.27/work/lazygit-0.27/src/github.com/jesseduffield/lazygit/pkg/utils/utils.go:380 +0x62
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunAndHandleError(0xc000082f00, 0x0, 0xb6b79f)
        /var/tmp/portage/dev-vcs/lazygit-0.27/work/lazygit-0.27/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:545 +0x7d
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc0002301c0, 0xc0001e67e0, 0x0)
        /var/tmp/portage/dev-vcs/lazygit-0.27/work/lazygit-0.27/src/github.com/jesseduffield/lazygit/pkg/app/app.go:242 +0x6b
main.main()
        /var/tmp/portage/dev-vcs/lazygit-0.27/work/lazygit-0.27/src/github.com/jesseduffield/lazygit/main.go:126 +0xb3b

```
The release of lazygit-0.26.1 isn't affected this issue.

**Comment by jesseduffield** [comment] 2021-04-07 23:20
closing as a dupe of https://github.com/jesseduffield/lazygit/issues/1229

I'll tackle this tonight though, should be an easy fix!

**Closed** 2021-04-07 23:20 UTC
Labels: bug
