### ISSUE TITLE
lazygit 0.35 regression test failure

### ISSUE THREAD

**Issue by chenrui333** [jesseduffield/lazygit#2043] opened 2022-07-20 21:04 UTC
**Describe the bug**

**To Reproduce**
1. download lazygit 0.35
2. run the test 
```
    touch git-rebase-todo
    export LAZYGIT_CLIENT_COMMAND =  "INTERACTIVE_REBASE"
    export LAZYGIT_REBASE_TODO = "foo"
    ./lazygit git-rebase-todo
```

You can see

```
$ lazygit git-rebase-todo
2022/07/20 17:00:55 Invalid git arg value: 'git-rebase-todo'. Must be one of the following values: status, branch, log, stash. e.g. 'lazygit status'. See 'lazygit --help'.
```

**Expected behavior**
pass

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Lazygit Version 0.35
 - The last commit id if you built project from sources (run : ```git rev-parse HEAD```)

**Additional context**
relates to https://github.com/Homebrew/homebrew-core/pull/106210

**Comment by jesseduffield** [comment] 2022-07-20 22:47
instead of `LAZYGIT_CLIENT_COMMAND` we now use `LAZYGIT_DAEMON_KIND`. The following works fine:
```sh
touch git-rebase-todo
export LAZYGIT_DAEMON_KIND=INTERACTIVE_REBASE
export LAZYGIT_REBASE_TODO=foo
lazygit git-rebase-todo
```

Is this a test that lives in that homebrew repo?

**Comment by natematykiewicz** [comment] 2022-07-20 23:10
Yup. Sounds like the problem is this line: https://github.com/Homebrew/homebrew-core/blob/master/Formula/lazygit.rb#L27

**Comment by jesseduffield** [comment] 2022-07-21 00:35
I've pushed a fix now

**Closed** 2022-07-22 20:06 UTC
Labels: bug
